//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ArenaDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaPlayerData")]
  public partial class ArenaPlayerData : global::ProtoBuf.IExtensible
  {
    public ArenaPlayerData() {}
    
    private int _charid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _role = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int role
    {
      get { return _role; }
      set { _role = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _equipid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"equipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equipid
    {
      get { return _equipid; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _Skillid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"Skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Skillid
    {
      get { return _Skillid; }
    }
  
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _rewardtime = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rewardtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardtime
    {
      get { return _rewardtime; }
      set { _rewardtime = value; }
    }
    private int _cooltime = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"cooltime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cooltime
    {
      get { return _cooltime; }
      set { _cooltime = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _report = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(11, Name=@"report", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> report
    {
      get { return _report; }
    }
  
    private int _fightforce = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fightforce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightforce
    {
      get { return _fightforce; }
      set { _fightforce = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankPlayData")]
  public partial class RankPlayData : global::ProtoBuf.IExtensible
  {
    public RankPlayData() {}
    
    private int _charid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _fightforce = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fightforce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightforce
    {
      get { return _fightforce; }
      set { _fightforce = value; }
    }
    private int _credits = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"credits", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int credits
    {
      get { return _credits; }
      set { _credits = value; }
    }
    private int _mingjie = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mingjie", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mingjie
    {
      get { return _mingjie; }
      set { _mingjie = value; }
    }
    private int _chengwei = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chengwei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chengwei
    {
      get { return _chengwei; }
      set { _chengwei = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaReportData")]
  public partial class ArenaReportData : global::ProtoBuf.IExtensible
  {
    public ArenaReportData() {}
    
    private bool _IsWin = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IsWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsWin
    {
      get { return _IsWin; }
      set { _IsWin = value; }
    }
    private bool _Attack = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Attack
    {
      get { return _Attack; }
      set { _Attack = value; }
    }
    private string _othername = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"othername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string othername
    {
      get { return _othername; }
      set { _othername = value; }
    }
    private int _ranking = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaGiveData")]
  public partial class ArenaGiveData : global::ProtoBuf.IExtensible
  {
    public ArenaGiveData() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}