//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AuguryCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuguryData")]
  public partial class AuguryData : global::ProtoBuf.IExtensible
  {
    public AuguryData() {}
    
    private uint _augury_count = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"augury_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint augury_count
    {
      get { return _augury_count; }
      set { _augury_count = value; }
    }
    private uint _free_change_count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"free_change_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint free_change_count
    {
      get { return _free_change_count; }
      set { _free_change_count = value; }
    }
    private uint _change_count = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"change_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint change_count
    {
      get { return _change_count; }
      set { _change_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuguryRecord")]
  public partial class AuguryRecord : global::ProtoBuf.IExtensible
  {
    public AuguryRecord() {}
    
    private bool _enable = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable
    {
      get { return _enable; }
      set { _enable = value; }
    }
    private uint _bless_count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bless_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bless_count
    {
      get { return _bless_count; }
      set { _bless_count = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _ball = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ball", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ball
    {
      get { return _ball; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshAuguryListClientCmd")]
  public partial class RefreshAuguryListClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshAuguryListClientCmd() {}
    
    private ProtoCmd.AuguryData _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.AuguryData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private ProtoCmd.AuguryRecord _record = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.AuguryRecord record
    {
      get { return _record; }
      set { _record = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuguryClientCmd")]
  public partial class AuguryClientCmd : global::ProtoBuf.IExtensible
  {
    public AuguryClientCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateAuguryDataClientCmd")]
  public partial class UpdateAuguryDataClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateAuguryDataClientCmd() {}
    
    private ProtoCmd.AuguryData _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.AuguryData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateAuguryRecordClientCmd")]
  public partial class UpdateAuguryRecordClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateAuguryRecordClientCmd() {}
    
    private ProtoCmd.AuguryRecord _record = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.AuguryRecord record
    {
      get { return _record; }
      set { _record = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeFateClientCmd")]
  public partial class ChangeFateClientCmd : global::ProtoBuf.IExtensible
  {
    public ChangeFateClientCmd() {}
    
    private bool _is_free = (bool)true;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_free", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool is_free
    {
      get { return _is_free; }
      set { _is_free = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAuguryRewardClientCmd")]
  public partial class GetAuguryRewardClientCmd : global::ProtoBuf.IExtensible
  {
    public GetAuguryRewardClientCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FateBallType")]
    public enum FateBallType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_None", Value=0)]
      FateBallType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Yellow", Value=1)]
      FateBallType_Yellow = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Cyan", Value=2)]
      FateBallType_Cyan = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Blue", Value=3)]
      FateBallType_Blue = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Purple", Value=4)]
      FateBallType_Purple = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Orange", Value=5)]
      FateBallType_Orange = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Green", Value=6)]
      FateBallType_Green = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Red", Value=7)]
      FateBallType_Red = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FateBallType_Max", Value=8)]
      FateBallType_Max = 8
    }
  
}