//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChatCommand.proto
// Note: requires additional types generated from: ErrorCode.proto
// Note: requires additional types generated from: ItemDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatDestPlayerInfo")]
  public partial class ChatDestPlayerInfo : global::ProtoBuf.IExtensible
  {
    public ChatDestPlayerInfo() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _roleid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _facepic = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"facepic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint facepic
    {
      get { return _facepic; }
      set { _facepic = value; }
    }
    private string _signiture = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"signiture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string signiture
    {
      get { return _signiture; }
      set { _signiture = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMCmdData")]
  public partial class GMCmdData : global::ProtoBuf.IExtensible
  {
    public GMCmdData() {}
    
    private string _command = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string command
    {
      get { return _command; }
      set { _command = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMChatClientCmd")]
  public partial class GMChatClientCmd : global::ProtoBuf.IExtensible
  {
    public GMChatClientCmd() {}
    
    private ProtoCmd.GMCmdData _cmd_data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cmd_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.GMCmdData cmd_data
    {
      get { return _cmd_data; }
      set { _cmd_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatParams")]
  public partial class ChatParams : global::ProtoBuf.IExtensible
  {
    public ChatParams() {}
    
    private byte[] _inviter = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"inviter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] inviter
    {
      get { return _inviter; }
      set { _inviter = value; }
    }
    private byte[] _invitee = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"invitee", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] invitee
    {
      get { return _invitee; }
      set { _invitee = value; }
    }
    private int _param1 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private int _param2 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _param3 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param3
    {
      get { return _param3; }
      set { _param3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatTextClientCmd")]
  public partial class ChatTextClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatTextClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _sendPlayerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sendPlayerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sendPlayerid
    {
      get { return _sendPlayerid; }
      set { _sendPlayerid = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private bool _is_recruit = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_recruit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_recruit
    {
      get { return _is_recruit; }
      set { _is_recruit = value; }
    }
    private ProtoCmd.ChatParams _chat_params = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chat_params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ChatParams chat_params
    {
      get { return _chat_params; }
      set { _chat_params = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatReturnTextClientCmd")]
  public partial class ChatReturnTextClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatReturnTextClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ProtoCmd.ErrorCode _errCode = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonChatClientCmd")]
  public partial class CommonChatClientCmd : global::ProtoBuf.IExtensible
  {
    public CommonChatClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private string _playername = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playername
    {
      get { return _playername; }
      set { _playername = value; }
    }
    private uint _role = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role
    {
      get { return _role; }
      set { _role = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private bool _is_recruit = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is_recruit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_recruit
    {
      get { return _is_recruit; }
      set { _is_recruit = value; }
    }
    private ProtoCmd.ChatParams _chat_params = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"chat_params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ChatParams chat_params
    {
      get { return _chat_params; }
      set { _chat_params = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatOpenPrivateWndClientCmd")]
  public partial class ChatOpenPrivateWndClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatOpenPrivateWndClientCmd() {}
    
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private ProtoCmd.ChatDestPlayerInfo _playerinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ChatDestPlayerInfo playerinfo
    {
      get { return _playerinfo; }
      set { _playerinfo = value; }
    }
    private ProtoCmd.ErrorCode _errCode = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatPrivateClientCmd")]
  public partial class ChatPrivateClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatPrivateClientCmd() {}
    
    private string _srcPlayername = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"srcPlayername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string srcPlayername
    {
      get { return _srcPlayername; }
      set { _srcPlayername = value; }
    }
    private string _destPlayerName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"destPlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string destPlayerName
    {
      get { return _destPlayerName; }
      set { _destPlayerName = value; }
    }
    private uint _src_role = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"src_role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_role
    {
      get { return _src_role; }
      set { _src_role = value; }
    }
    private uint _src_level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"src_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_level
    {
      get { return _src_level; }
      set { _src_level = value; }
    }
    private uint _src_vip = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"src_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_vip
    {
      get { return _src_vip; }
      set { _src_vip = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private ProtoCmd.ErrorCode _errCode = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private ProtoCmd.ChatParams _chat_params = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chat_params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ChatParams chat_params
    {
      get { return _chat_params; }
      set { _chat_params = value; }
    }
    private uint _src_playerid = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"src_playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_playerid
    {
      get { return _src_playerid; }
      set { _src_playerid = value; }
    }
    private uint _dest_playerid = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dest_playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_playerid
    {
      get { return _dest_playerid; }
      set { _dest_playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatSysClientCmd")]
  public partial class ChatSysClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatSysClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _itemid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatItemShowClientCmd")]
  public partial class ChatItemShowClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatItemShowClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _sendplayerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sendplayerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sendplayerid
    {
      get { return _sendplayerid; }
      set { _sendplayerid = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _itemThisid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"itemThisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> itemThisid
    {
      get { return _itemThisid; }
    }
  
    private string _data = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatReturnItemShowClientCmd")]
  public partial class ChatReturnItemShowClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatReturnItemShowClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> _Items = new global::System.Collections.Generic.List<ProtoCmd.ItemSerialize>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> Items
    {
      get { return _Items; }
    }
  
    private ProtoCmd.ErrorCode _errCode = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatType_Client")]
    public enum ChatType_Client
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_None", Value=0)]
      ChatType_C_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_All", Value=1)]
      ChatType_C_Client_All = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Nearby", Value=4)]
      ChatType_C_Nearby = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Map", Value=8)]
      ChatType_C_Map = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_AllyCountry", Value=16)]
      ChatType_C_AllyCountry = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Team", Value=32)]
      ChatType_C_Team = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Army", Value=64)]
      ChatType_C_Army = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Country", Value=128)]
      ChatType_C_Country = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_World", Value=256)]
      ChatType_C_World = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_PrivateChannel", Value=512)]
      ChatType_C_Client_PrivateChannel = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_PrivateWnd", Value=1024)]
      ChatType_C_Client_PrivateWnd = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_UsrDefine", Value=2048)]
      ChatType_C_Client_UsrDefine = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Horn", Value=4096)]
      ChatType_C_Horn = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Sociaty", Value=8192)]
      ChatType_C_Sociaty = 8192,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_GM", Value=16384)]
      ChatType_C_GM = 16384,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Sys", Value=32768)]
      ChatType_C_Sys = 32768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_MsgBox", Value=65536)]
      ChatType_C_MsgBox = 65536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Center", Value=131072)]
      ChatType_C_Center = 131072
    }
  
}