//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Command.proto
namespace ProtoCmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CmdNumber")]
    public enum CmdNumber
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientCmdNone", Value=0)]
      ClientCmdNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerVerifyVerLoginClientCmd_C", Value=1)]
      PlayerVerifyVerLoginClientCmd_C = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginAccessLoginClientCmd_C", Value=2)]
      LoginAccessLoginClientCmd_C = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerRequestLoginClientCmd_C", Value=3)]
      PlayerRequestLoginClientCmd_C = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerReturnLoginClientCmd_S", Value=4)]
      ServerReturnLoginClientCmd_S = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerReturnLoginSuccessLoginClientCmd_S", Value=5)]
      ServerReturnLoginSuccessLoginClientCmd_S = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerListSelectClientCmd_S", Value=6)]
      PlayerListSelectClientCmd_S = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheckNameSelectClientCmd_CS", Value=7)]
      CheckNameSelectClientCmd_CS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateSelectClientCmd_C", Value=8)]
      CreateSelectClientCmd_C = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeleteSelectClientCmd_C", Value=9)]
      DeleteSelectClientCmd_C = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnDeleteSelectClientCmd_S", Value=10)]
      ReturnDeleteSelectClientCmd_S = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateSelectResultClientCmd_S", Value=11)]
      CreateSelectResultClientCmd_S = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginStepSelectClientCmd_S", Value=12)]
      LoginStepSelectClientCmd_S = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerSelectClientCmd_C", Value=13)]
      PlayerSelectClientCmd_C = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectReturnSelectClientCmd_S", Value=14)]
      SelectReturnSelectClientCmd_S = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRandomRoleNameClientCmd_CS", Value=15)]
      CreateRandomRoleNameClientCmd_CS = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccountRegisterClientCmd_CS", Value=16)]
      AccountRegisterClientCmd_CS = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFreshPlayerCmd_CS", Value=17)]
      ReqFreshPlayerCmd_CS = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTest_CS", Value=18)]
      ReqTest_CS = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqInitDeviceCmd_C", Value=19)]
      ReqInitDeviceCmd_C = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HintClientCmd_S", Value=20)]
      HintClientCmd_S = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspErrorCmd_S", Value=21)]
      RspErrorCmd_S = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestPingClientCmd_C", Value=22)]
      RequestPingClientCmd_C = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondPingClientCmd_S", Value=23)]
      RespondPingClientCmd_S = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReconnectLoginClientCmd_C", Value=24)]
      ReconnectLoginClientCmd_C = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnReconnectLoginClientCmd_S", Value=25)]
      ReturnReconnectLoginClientCmd_S = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendReconnectKeyClientCmd_S", Value=26)]
      SendReconnectKeyClientCmd_S = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqActivateAccountClientCmd_C", Value=27)]
      ReqActivateAccountClientCmd_C = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqChangeCharNameClientCmd_C", Value=28)]
      ReqChangeCharNameClientCmd_C = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspChangeCharNameClientCmd_S", Value=29)]
      RspChangeCharNameClientCmd_S = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenFunctionClientCmd_S", Value=30)]
      OpenFunctionClientCmd_S = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateQueueNumClientCmd_S", Value=31)]
      UpdateQueueNumClientCmd_S = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAdvanceClientCmd_C", Value=40)]
      EquipAdvanceClientCmd_C = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveStoneAdvanceClientCmd_C", Value=41)]
      EquipImproveStoneAdvanceClientCmd_C = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshEquipPartListClientCmd_S", Value=42)]
      RefreshEquipPartListClientCmd_S = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateEquipPartClientCmd_S", Value=43)]
      UpdateEquipPartClientCmd_S = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultEquipDecomposeClientCmd_S", Value=44)]
      ResultEquipDecomposeClientCmd_S = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveFuseClientCmd_C", Value=45)]
      EquipImproveFuseClientCmd_C = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WingAdvanceClientCmd_C", Value=46)]
      WingAdvanceClientCmd_C = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StrengthenWeaponClientCmd_C", Value=47)]
      StrengthenWeaponClientCmd_C = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqWingSwapClientCmd_C", Value=48)]
      ReqWingSwapClientCmd_C = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemListItemClientCmd_S", Value=50)]
      AddItemListItemClientCmd_S = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddDataItemClientCmd_S", Value=51)]
      AddDataItemClientCmd_S = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveDataItemClientCmd_CS", Value=52)]
      RemoveDataItemClientCmd_CS = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwapItemClientCmd_CS", Value=53)]
      SwapItemClientCmd_CS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SplitItemClientCmd_C", Value=54)]
      SplitItemClientCmd_C = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnionItemClientCmd_C", Value=55)]
      UnionItemClientCmd_C = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshCountItemClientCmd_S", Value=56)]
      RefreshCountItemClientCmd_S = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshLocationItemClientCmd_S", Value=57)]
      RefreshLocationItemClientCmd_S = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseItemClientCmd_C", Value=58)]
      UseItemClientCmd_C = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveItemClientCmd_C", Value=59)]
      MoveItemClientCmd_C = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResponseItemOperationItemClientCmd_S", Value=60)]
      ResponseItemOperationItemClientCmd_S = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseItemToNpcClientCmd_C", Value=61)]
      UseItemToNpcClientCmd_C = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SellItemClientCmd_C", Value=62)]
      SellItemClientCmd_C = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveResponseClientCmd_S", Value=65)]
      EquipImproveResponseClientCmd_S = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveReformClientCmd_CS", Value=66)]
      EquipImproveReformClientCmd_CS = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveTransferClientCmd_C", Value=67)]
      EquipImproveTransferClientCmd_C = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveStrengthenClientCmd_C", Value=68)]
      EquipImproveStrengthenClientCmd_C = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveInlayClientCmd_C", Value=69)]
      EquipImproveInlayClientCmd_C = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveDecomposeClientCmd_C", Value=70)]
      EquipImproveDecomposeClientCmd_C = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveStoneConvertClientCmd_C", Value=71)]
      EquipImproveStoneConvertClientCmd_C = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveMergeClientCmd_C", Value=72)]
      EquipImproveMergeClientCmd_C = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveTakeOutStoneClientCmd_C", Value=73)]
      EquipImproveTakeOutStoneClientCmd_C = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshEquipSuitAttrClientCmd_S", Value=74)]
      RefreshEquipSuitAttrClientCmd_S = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveReformConfirmClientCmd_C", Value=75)]
      EquipImproveReformConfirmClientCmd_C = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveReformResultClientCmd_S", Value=76)]
      EquipImproveReformResultClientCmd_S = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchSellItemClientCmd_C", Value=78)]
      BatchSellItemClientCmd_C = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondPingClientCmd_C", Value=80)]
      RespondPingClientCmd_C = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestPingClientCmd_S", Value=81)]
      RequestPingClientCmd_S = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMsgClientCmd_S", Value=82)]
      RespondMsgClientCmd_S = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogoutClientCmd_C", Value=83)]
      LogoutClientCmd_C = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetTokenCommand_C", Value=84)]
      ReqGetTokenCommand_C = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetTokenCommand_S", Value=85)]
      RspGetTokenCommand_S = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPayForGoodsCommand_C", Value=86)]
      ReqPayForGoodsCommand_C = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPayForGoodsCommand_S", Value=87)]
      RspPayForGoodsCommand_S = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetChargeResultCommand_C", Value=88)]
      ReqGetChargeResultCommand_C = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQueryPayKeyCommand_C", Value=89)]
      ReqQueryPayKeyCommand_C = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQueryPayKeyCommand_S", Value=90)]
      RspQueryPayKeyCommand_S = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPlatSDKInfoCommand_S", Value=91)]
      RspPlatSDKInfoCommand_S = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMChatClientCmd_C", Value=100)]
      GMChatClientCmd_C = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CommonChatClientCmd_S", Value=101)]
      CommonChatClientCmd_S = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatSysClientCmd_S", Value=102)]
      ChatSysClientCmd_S = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatPrivateClientCmd_CS", Value=103)]
      ChatPrivateClientCmd_CS = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatItemShowClientCmd_C", Value=104)]
      ChatItemShowClientCmd_C = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatReturnItemShowClientCmd_S", Value=105)]
      ChatReturnItemShowClientCmd_S = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatTextClientCmd_C", Value=106)]
      ChatTextClientCmd_C = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatReturnTextClientCmd_S", Value=107)]
      ChatReturnTextClientCmd_S = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatOpenPrivateWndClientCmd_CS", Value=108)]
      ChatOpenPrivateWndClientCmd_CS = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SortPackageClientCmd_CS", Value=140)]
      SortPackageClientCmd_CS = 140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetPackageGridPackageClientCmd_S", Value=141)]
      SetPackageGridPackageClientCmd_S = 141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExtendCapacityPackageClientCmd_CS", Value=142)]
      ExtendCapacityPackageClientCmd_CS = 142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMoneyDataClientCmd_S", Value=150)]
      RefreshMoneyDataClientCmd_S = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoneyChangeClientCmd_S", Value=151)]
      MoneyChangeClientCmd_S = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePlayerMainDataClientCmd_S", Value=152)]
      UpdatePlayerMainDataClientCmd_S = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateHpClientCmd_S", Value=153)]
      UpdateHpClientCmd_S = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateSoldierClientCmd_S", Value=154)]
      UpdateSoldierClientCmd_S = 154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateLevelExpDataClientCmd_S", Value=155)]
      UpdateLevelExpDataClientCmd_S = 155,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateSysSetDataClientCmd_C", Value=156)]
      UpdateSysSetDataClientCmd_C = 156,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateClientConfigDataClientCmd_C", Value=157)]
      UpdateClientConfigDataClientCmd_C = 157,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResponseRideVehicleClientCmd_S", Value=159)]
      ResponseRideVehicleClientCmd_S = 159,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddExpDataTipsClientCmd_S", Value=160)]
      AddExpDataTipsClientCmd_S = 160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddMoneyDataTipsClientCmd_S", Value=161)]
      AddMoneyDataTipsClientCmd_S = 161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncLogicConfigParamClientCmd_S", Value=162)]
      SyncLogicConfigParamClientCmd_S = 162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSelectedInfoDataClientCmd_S", Value=163)]
      RefreshSelectedInfoDataClientCmd_S = 163,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshWerwolfDataClientCmd_S", Value=164)]
      RefreshWerwolfDataClientCmd_S = 164,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncMoonClientCmd_S", Value=165)]
      SyncMoonClientCmd_S = 165,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WerwolfRestoreClientCmd_S", Value=166)]
      WerwolfRestoreClientCmd_S = 166,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResponseWerwolfOperationClientCmd_S", Value=167)]
      ResponseWerwolfOperationClientCmd_S = 167,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WerwolfTransferClientCmd_C", Value=168)]
      WerwolfTransferClientCmd_C = 168,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResponseWerwolfTransferClientCmd_S", Value=169)]
      ResponseWerwolfTransferClientCmd_S = 169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePhysicalClientCmd_S", Value=170)]
      UpdatePhysicalClientCmd_S = 170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateCreditsClientCmd_S", Value=171)]
      UpdateCreditsClientCmd_S = 171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateCourageClientCmd_S", Value=172)]
      UpdateCourageClientCmd_S = 172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePvpPowerClientCmd_S", Value=173)]
      UpdatePvpPowerClientCmd_S = 173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncTime_S", Value=174)]
      SyncTime_S = 174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateAngryClientCmd_S", Value=175)]
      UpdateAngryClientCmd_S = 175,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateContribClientCmd_S", Value=176)]
      UpdateContribClientCmd_S = 176,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateBattleScoreClientCmd_S", Value=177)]
      UpdateBattleScoreClientCmd_S = 177,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMailOperateClientCmd_S", Value=180)]
      RespondMailOperateClientCmd_S = 180,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMailListClientCmd_S", Value=181)]
      RefreshMailListClientCmd_S = 181,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadMailClientCmd_C", Value=182)]
      ReadMailClientCmd_C = 182,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateMailDataClientCmd_S", Value=183)]
      UpdateMailDataClientCmd_S = 183,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickMailItemClientCmd_C", Value=184)]
      PickMailItemClientCmd_C = 184,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMailClientCmd_C", Value=185)]
      SendMailClientCmd_C = 185,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelMailClientCmd_C", Value=186)]
      DelMailClientCmd_C = 186,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultDelMailClientCmd_S", Value=187)]
      ResultDelMailClientCmd_S = 187,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaOpenClientCmd_C", Value=200)]
      ArenaOpenClientCmd_C = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFightReportClientCmd_C", Value=201)]
      RequestFightReportClientCmd_C = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestArenaRankClientCmd_C", Value=202)]
      RequestArenaRankClientCmd_C = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaFightPlayerClientCmd_C", Value=203)]
      ArenaFightPlayerClientCmd_C = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RankRewardClientCmd_CS", Value=204)]
      RankRewardClientCmd_CS = 204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddArenaPlayerClientCmd_C", Value=205)]
      AddArenaPlayerClientCmd_C = 205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaReturnMatchClientCmd_S", Value=206)]
      ArenaReturnMatchClientCmd_S = 206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeArenaStartClientCmd_S", Value=207)]
      NoticeArenaStartClientCmd_S = 207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeMatchDispartClientCmd_S", Value=208)]
      NoticeMatchDispartClientCmd_S = 208,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRankListClientCmd_C", Value=213)]
      GetRankListClientCmd_C = 213,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRankListClientCmd_S", Value=214)]
      UpdateRankListClientCmd_S = 214,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSacrificeRankClientCmd_C", Value=215)]
      ReqSacrificeRankClientCmd_C = 215,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSacrificeRankClientCmd_S", Value=216)]
      RspSacrificeRankClientCmd_S = 216,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetBattleScoreRankListClientCmd_C", Value=217)]
      GetBattleScoreRankListClientCmd_C = 217,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendBattleScoreRankListCmd_S", Value=218)]
      SendBattleScoreRankListCmd_S = 218,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetOtherWorldRankListClientCmd_C", Value=219)]
      GetOtherWorldRankListClientCmd_C = 219,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendOtherWorldScoreRankListCmd_S", Value=220)]
      SendOtherWorldScoreRankListCmd_S = 220,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBattleScoreRankClientCmd_CS", Value=221)]
      ReqBattleScoreRankClientCmd_CS = 221,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestQuestClientCmd_S", Value=250)]
      SendQuestQuestClientCmd_S = 250,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestElementQuestClientCmd_S", Value=251)]
      SendQuestElementQuestClientCmd_S = 251,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestListQuestClientCmd_S", Value=252)]
      SendQuestListQuestClientCmd_S = 252,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestElementListQuestClientCmd_S", Value=253)]
      SendQuestElementListQuestClientCmd_S = 253,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQuestStateQuestClientCmd_S", Value=254)]
      RefreshQuestStateQuestClientCmd_S = 254,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQuestElementStateQuestClientCmd_S", Value=255)]
      RefreshQuestElementStateQuestClientCmd_S = 255,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelQuestQuestClientCmd_CS", Value=256)]
      DelQuestQuestClientCmd_CS = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelQuestElementQuestClientCmd_CS", Value=257)]
      DelQuestElementQuestClientCmd_CS = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAcceptQuestQuestClientCmd_C", Value=258)]
      RequestAcceptQuestQuestClientCmd_C = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishQuestQuestClientCmd_C", Value=259)]
      RequestFinishQuestQuestClientCmd_C = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAcceptQuestElementQuestClientCmd_C", Value=260)]
      RequestAcceptQuestElementQuestClientCmd_C = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishQuestElementQuestClientCmd_C", Value=261)]
      RequestFinishQuestElementQuestClientCmd_C = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestNotifyQuestClientCmd_S", Value=262)]
      QuestNotifyQuestClientCmd_S = 262,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClearLoopCounterQuestClientCmd_S", Value=263)]
      ClearLoopCounterQuestClientCmd_S = 263,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FindNPCQuestClientCmd_C", Value=264)]
      FindNPCQuestClientCmd_C = 264,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSkillSkillClientCmd_S", Value=280)]
      RefreshSkillSkillClientCmd_S = 280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LearnSkillClientCmd_CS", Value=281)]
      LearnSkillClientCmd_CS = 281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveSkillClientCmd_S", Value=282)]
      RemoveSkillClientCmd_S = 282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeUseSkillClientCmd_CS", Value=283)]
      ChangeUseSkillClientCmd_CS = 283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OperSkillClientCmd_CS", Value=284)]
      OperSkillClientCmd_CS = 284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClearPointSkillClientCmd_CS", Value=285)]
      ClearPointSkillClientCmd_CS = 285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshUseSkillSkillClientCmd_S", Value=286)]
      RefreshUseSkillSkillClientCmd_S = 286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddSkillClientCmd_S", Value=287)]
      AddSkillClientCmd_S = 287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RecoverSkillLearnTimeClientCmd_CS", Value=288)]
      RecoverSkillLearnTimeClientCmd_CS = 288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSkillLearnTimeClientCmd_S", Value=289)]
      RefreshSkillLearnTimeClientCmd_S = 289,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestSkillLevelUpClientCmd_C", Value=270)]
      RequestSkillLevelUpClientCmd_C = 270,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestSwapSkillClientCmd_C", Value=271)]
      RequestSwapSkillClientCmd_C = 271,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateSkillClientCmd_S", Value=272)]
      UpdateSkillClientCmd_S = 272,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSkillLevelUpClientCmd_S", Value=273)]
      RspSkillLevelUpClientCmd_S = 273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchRemovePlayerMapScreenClientCmd_S", Value=300)]
      BatchRemovePlayerMapScreenClientCmd_S = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemovePlayerMapScreenClientCmd_S", Value=301)]
      RemovePlayerMapScreenClientCmd_S = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPlayerMapScreenClientCmd_S", Value=302)]
      AddPlayerMapScreenClientCmd_S = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchAddPlayerMapScreenClientCmd_S", Value=303)]
      BatchAddPlayerMapScreenClientCmd_S = 303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddMapMapScreenClientCmd_S", Value=304)]
      AddMapMapScreenClientCmd_S = 304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNpcMapScreenClientCmd_S", Value=305)]
      AddNpcMapScreenClientCmd_S = 305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveNpcMapScreenClientCmd_S", Value=306)]
      RemoveNpcMapScreenClientCmd_S = 306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchRemoveNpcMapScreenClientCmd_S", Value=307)]
      BatchRemoveNpcMapScreenClientCmd_S = 307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchAddNpcMapScreenClientCmd_S", Value=308)]
      BatchAddNpcMapScreenClientCmd_S = 308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddLostMapScreenClientCmd_S", Value=309)]
      AddLostMapScreenClientCmd_S = 309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveLostMapScreenClientCmd_S", Value=310)]
      RemoveLostMapScreenClientCmd_S = 310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchRemoveLostMapScreenClientCmd_S", Value=311)]
      BatchRemoveLostMapScreenClientCmd_S = 311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchAddLostMapScreenClientCmd_S", Value=312)]
      BatchAddLostMapScreenClientCmd_S = 312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResMapNpcItemLocalClientCmd_S", Value=322)]
      ResMapNpcItemLocalClientCmd_S = 322,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateMultyFbClientCmd_C", Value=323)]
      CreateMultyFbClientCmd_C = 323,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterMultyFbClientCmd_C", Value=324)]
      EnterMultyFbClientCmd_C = 324,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartEnterMultyFbClientCmd_CS", Value=325)]
      StartEnterMultyFbClientCmd_CS = 325,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetOutEnterMultyFbClientCmd_CS", Value=326)]
      SetOutEnterMultyFbClientCmd_CS = 326,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestCreateMultyFbClientCmd_C", Value=327)]
      RequestCreateMultyFbClientCmd_C = 327,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestEnterMultyFbClientCmd_C", Value=328)]
      RequestEnterMultyFbClientCmd_C = 328,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewPlayerInMultyFbClientCmd_S", Value=329)]
      NewPlayerInMultyFbClientCmd_S = 329,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MulteFbRoomListClientCmd_C", Value=290)]
      MulteFbRoomListClientCmd_C = 290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResMulteFbRoomListClientCmd_S", Value=291)]
      ResMulteFbRoomListClientCmd_S = 291,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MulteFbInfoClientCmd_S", Value=292)]
      MulteFbInfoClientCmd_S = 292,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KickingPlayerClientCmd_CS", Value=293)]
      KickingPlayerClientCmd_CS = 293,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShowAllFbListClientCmd_C", Value=295)]
      ShowAllFbListClientCmd_C = 295,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResShowAllFbListClientCmd_S", Value=296)]
      ResShowAllFbListClientCmd_S = 296,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChooseFbClientCmd_CS", Value=297)]
      ChooseFbClientCmd_CS = 297,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShowPlayerListClientCmd_CS", Value=298)]
      ShowPlayerListClientCmd_CS = 298,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InvitePlayerEnterFbClientCmd_CS", Value=299)]
      InvitePlayerEnterFbClientCmd_CS = 299,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LeaveMultyFbClientCmd_CS", Value=330)]
      LeaveMultyFbClientCmd_CS = 330,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetRoomPasswordClientCmd_CS", Value=331)]
      SetRoomPasswordClientCmd_CS = 331,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFastTeamFbClientCmd_C", Value=332)]
      RequestFastTeamFbClientCmd_C = 332,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestCreatePvpFbClientCmd_C", Value=334)]
      RequestCreatePvpFbClientCmd_C = 334,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestJoinPvpFbClientCmd_C", Value=367)]
      RequestJoinPvpFbClientCmd_C = 367,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPVPDataCmd_S", Value=368)]
      SendPVPDataCmd_S = 368,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendEnterPVPCountDownCmd_S", Value=369)]
      SendEnterPVPCountDownCmd_S = 369,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendCreatePVPSuccCmd_S", Value=370)]
      SendCreatePVPSuccCmd_S = 370,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendCancelPVPCmd_CS", Value=371)]
      SendCancelPVPCmd_CS = 371,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPVPEnemyDataCmd_S", Value=372)]
      SendPVPEnemyDataCmd_S = 372,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerMoveClientCmd_C", Value=335)]
      PlayerMoveClientCmd_C = 335,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RetPlayerMoveClientCmd_S", Value=336)]
      RetPlayerMoveClientCmd_S = 336,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerMoveFailClientCmd_S", Value=337)]
      PlayerMoveFailClientCmd_S = 337,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcMoveClientCmd_S", Value=338)]
      NpcMoveClientCmd_S = 338,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerTransmitMoveClientCmd_C", Value=339)]
      PlayerTransmitMoveClientCmd_C = 339,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemMonsterMapScreenClientCmd_S", Value=340)]
      AddItemMonsterMapScreenClientCmd_S = 340,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDeathTowerRankingClientCmd_C", Value=341)]
      ReqDeathTowerRankingClientCmd_C = 341,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDeathTowerRankingClientCmd_S", Value=342)]
      RspDeathTowerRankingClientCmd_S = 342,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqChallengeNextLayerClientCmd_C", Value=343)]
      ReqChallengeNextLayerClientCmd_C = 343,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRefreshDeathTowerClientCmd_C", Value=344)]
      ReqRefreshDeathTowerClientCmd_C = 344,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRefreshDeathTowerClientCmd_S", Value=345)]
      RspRefreshDeathTowerClientCmd_S = 345,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MonsterLostItemClientCmd_S", Value=354)]
      MonsterLostItemClientCmd_S = 354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestCreateGuildClientCmd_C", Value=400)]
      RequestCreateGuildClientCmd_C = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeGuildStrInfoGuildClientCmd_C", Value=401)]
      ChangeGuildStrInfoGuildClientCmd_C = 401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeLeaderGuildClientCmd_C", Value=402)]
      ChangeLeaderGuildClientCmd_C = 402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuildListGuildClientCmd_C", Value=403)]
      ReqGuildListGuildClientCmd_C = 403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuitGuildGuildClientCmd_C", Value=404)]
      QuitGuildGuildClientCmd_C = 404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KickMemberGuildClientCmd_C", Value=405)]
      KickMemberGuildClientCmd_C = 405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ApplyGuildGuildClientCmd_C", Value=406)]
      ApplyGuildGuildClientCmd_C = 406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcceptPlayerGuildClientCmd_C", Value=407)]
      AcceptPlayerGuildClientCmd_C = 407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InvitePlayerGuildClientCmd_C", Value=408)]
      InvitePlayerGuildClientCmd_C = 408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcceptInviteGuildClientCmd_C", Value=409)]
      AcceptInviteGuildClientCmd_C = 409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPlayerApplyDataGuildClientCmd_C", Value=410)]
      ReqPlayerApplyDataGuildClientCmd_C = 410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUpgradeGuildClientCmd_C", Value=411)]
      ReqUpgradeGuildClientCmd_C = 411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqEventGuildClientCmd_C", Value=412)]
      ReqEventGuildClientCmd_C = 412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangePositionGuildClientCmd_C", Value=413)]
      ChangePositionGuildClientCmd_C = 413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLevelRankGuildClientCmd_C", Value=414)]
      ReqLevelRankGuildClientCmd_C = 414,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelApplyGuildGuildClientCmd_C", Value=415)]
      CancelApplyGuildGuildClientCmd_C = 415,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPlayerRankGuildClientCmd_C", Value=416)]
      ReqPlayerRankGuildClientCmd_C = 416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuildFindGuildClientCmd_C", Value=417)]
      ReqGuildFindGuildClientCmd_C = 417,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLevelRankGuildClientCmd_S", Value=420)]
      RspLevelRankGuildClientCmd_S = 420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BaseDataGuildClientCmd_S", Value=421)]
      BaseDataGuildClientCmd_S = 421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateMemberListGuildClientCmd_S", Value=422)]
      UpdateMemberListGuildClientCmd_S = 422,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReplyGuildListGuildClientCmd_S", Value=423)]
      ReplyGuildListGuildClientCmd_S = 423,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerApply2OfficerGuildClientCmd_S", Value=424)]
      PlayerApply2OfficerGuildClientCmd_S = 424,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeApplyGuildSucClientCmd_S", Value=425)]
      NoticeApplyGuildSucClientCmd_S = 425,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeAddGuildSucClientCmd_S", Value=426)]
      NoticeAddGuildSucClientCmd_S = 426,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeBeKickClientCmd_S", Value=427)]
      NoticeBeKickClientCmd_S = 427,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeCancelApplyGuildSucClientCmd_S", Value=428)]
      NoticeCancelApplyGuildSucClientCmd_S = 428,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspEventGuildClientCmd_S", Value=429)]
      RspEventGuildClientCmd_S = 429,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCreateGuildClientCmd_S", Value=430)]
      RspCreateGuildClientCmd_S = 430,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQuitGuildGuildClientCmd_S", Value=431)]
      RspQuitGuildGuildClientCmd_S = 431,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelMemberListGuildClientCmd_S", Value=432)]
      DelMemberListGuildClientCmd_S = 432,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPlayerRankGuildClientCmd_S", Value=433)]
      RspPlayerRankGuildClientCmd_S = 433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSetAutoJoinGuildCmd_C", Value=434)]
      ReqSetAutoJoinGuildCmd_C = 434,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSetAutoJoinGuildCmd_S", Value=435)]
      RspSetAutoJoinGuildCmd_S = 435,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspJoinGuildCmd_S", Value=436)]
      RspJoinGuildCmd_S = 436,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGuildFindGuildClientCmd_S", Value=437)]
      RspGuildFindGuildClientCmd_S = 437,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMineInfoGuildClientCmd_S", Value=440)]
      SendMineInfoGuildClientCmd_S = 440,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuildMinePetWorkClientCmd_C", Value=441)]
      ReqGuildMinePetWorkClientCmd_C = 441,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuildMineOperateClientCmd_C", Value=442)]
      ReqGuildMineOperateClientCmd_C = 442,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetGuildBossHurtRankClientCmd_C", Value=445)]
      ReqGetGuildBossHurtRankClientCmd_C = 445,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetGuildBossHurtRankClientCmd_S", Value=446)]
      RspGetGuildBossHurtRankClientCmd_S = 446,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshStoryListClientCmd_S", Value=450)]
      RefreshStoryListClientCmd_S = 450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishStoryClientCmd_C", Value=451)]
      RequestFinishStoryClientCmd_C = 451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFinishStoryClientCmd_S", Value=452)]
      AddFinishStoryClientCmd_S = 452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddDoingStoryClientCmd_S", Value=453)]
      AddDoingStoryClientCmd_S = 453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaExchangeClientCmd_C", Value=480)]
      ArenaExchangeClientCmd_C = 480,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaShopOpenClientCmd_C", Value=481)]
      ArenaShopOpenClientCmd_C = 481,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaBuyGoodsClientCmd_C", Value=482)]
      ArenaBuyGoodsClientCmd_C = 482,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetArenaShopClientCmd_C", Value=483)]
      GetArenaShopClientCmd_C = 483,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MallOpenClientCmd_C", Value=500)]
      MallOpenClientCmd_C = 500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMallClientCmd_C", Value=501)]
      RefreshMallClientCmd_C = 501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MallItemBuyClientCmd_C", Value=504)]
      MallItemBuyClientCmd_C = 504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMallOpenClientCmd_S", Value=505)]
      RespondMallOpenClientCmd_S = 505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMallOperateClientCmd_S", Value=506)]
      RespondMallOperateClientCmd_S = 506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateMallItemClientCmd_S", Value=507)]
      UpdateMallItemClientCmd_S = 507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotifyMallCanRefreshClientCmd_S", Value=508)]
      NotifyMallCanRefreshClientCmd_S = 508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogSearchDateCliendCmd_C", Value=510)]
      LogSearchDateCliendCmd_C = 510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReLogSearchDateClientCmd_S", Value=511)]
      ReLogSearchDateClientCmd_S = 511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartAnalyseFileClientCmd_C", Value=512)]
      StartAnalyseFileClientCmd_C = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReLogStartAnalyseFileClientCmd_S", Value=513)]
      ReLogStartAnalyseFileClientCmd_S = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMerchantDataClientCmd_S", Value=520)]
      RefreshMerchantDataClientCmd_S = 520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OpenBusinessListClientCmd_C", Value=521)]
      OpenBusinessListClientCmd_C = 521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshBusinessListClientCmd_S", Value=522)]
      RefreshBusinessListClientCmd_S = 522,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshBusinessQualityClientCmd_C", Value=523)]
      RefreshBusinessQualityClientCmd_C = 523,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyBusinessInsureClientCmd_C", Value=524)]
      BuyBusinessInsureClientCmd_C = 524,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartBusinessClientCmd_C", Value=525)]
      StartBusinessClientCmd_C = 525,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuickBusinessClientCmd_C", Value=526)]
      QuickBusinessClientCmd_C = 526,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndBusinessClientCmd_C", Value=527)]
      EndBusinessClientCmd_C = 527,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BusinessRewardClientCmd_S", Value=528)]
      BusinessRewardClientCmd_S = 528,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RobBusinessClientCmd_CS", Value=529)]
      RobBusinessClientCmd_CS = 529,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateBusinessDataClientCmd_S", Value=531)]
      UpdateBusinessDataClientCmd_S = 531,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelBusinessDataClientCmd_S", Value=532)]
      DelBusinessDataClientCmd_S = 532,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateBusinessQualityClientCmd_S", Value=533)]
      UpdateBusinessQualityClientCmd_S = 533,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshAuguryListClientCmd_S", Value=534)]
      RefreshAuguryListClientCmd_S = 534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AuguryClientCmd_C", Value=535)]
      AuguryClientCmd_C = 535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateAuguryDataClientCmd_S", Value=536)]
      UpdateAuguryDataClientCmd_S = 536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateAuguryRecordClientCmd_S", Value=537)]
      UpdateAuguryRecordClientCmd_S = 537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeFateClientCmd_C", Value=538)]
      ChangeFateClientCmd_C = 538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetAuguryRewardClientCmd_C", Value=539)]
      GetAuguryRewardClientCmd_C = 539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReduceRobBusinessCDClientCmd_C", Value=540)]
      ReduceRobBusinessCDClientCmd_C = 540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshRobLogListClientCmd_S", Value=541)]
      RefreshRobLogListClientCmd_S = 541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddRobLogClientCmd_S", Value=542)]
      AddRobLogClientCmd_S = 542,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestEnterFbClientCmd_C", Value=600)]
      RequestEnterFbClientCmd_C = 600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqEnterSceneCmd_C", Value=601)]
      ReqEnterSceneCmd_C = 601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestLeaveFbClientCmd_C", Value=602)]
      RequestLeaveFbClientCmd_C = 602,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FbSettlementDataCmd_S", Value=603)]
      FbSettlementDataCmd_S = 603,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FbBattleFieldSettlementDataCmd_S", Value=604)]
      FbBattleFieldSettlementDataCmd_S = 604,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CastSkillClientCmd_C", Value=608)]
      CastSkillClientCmd_C = 608,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TrapClientCmd_C", Value=609)]
      TrapClientCmd_C = 609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncSkillToOtherCmd_CS", Value=610)]
      SyncSkillToOtherCmd_CS = 610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncHpCmd_S", Value=615)]
      SyncHpCmd_S = 615,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendFbVerifyFlagCmd_S", Value=616)]
      SendFbVerifyFlagCmd_S = 616,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncBuffCmd_S", Value=617)]
      SyncBuffCmd_S = 617,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FbYuanSuDongXueElementClientCmd_S", Value=618)]
      FbYuanSuDongXueElementClientCmd_S = 618,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendTriggerActivityClientCmd_S", Value=619)]
      SendTriggerActivityClientCmd_S = 619,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFightPropCmd_S", Value=620)]
      UpdateFightPropCmd_S = 620,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLeaveFbClientCmd_S", Value=621)]
      RspLeaveFbClientCmd_S = 621,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendBattleFieldScore_S", Value=622)]
      SendBattleFieldScore_S = 622,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendFbCamp_S", Value=623)]
      SendFbCamp_S = 623,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendWarRuneCmd_S", Value=624)]
      SendWarRuneCmd_S = 624,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendClearSkillCoolTimeCmd_S", Value=625)]
      SendClearSkillCoolTimeCmd_S = 625,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WeekRechargeClientCmd_S", Value=626)]
      WeekRechargeClientCmd_S = 626,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PushStarGiftClientCmd_S", Value=627)]
      PushStarGiftClientCmd_S = 627,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShareBlogClientCmd_C", Value=628)]
      ShareBlogClientCmd_C = 628,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelTakenGiftClientCmd_S", Value=629)]
      DelTakenGiftClientCmd_S = 629,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshAllGiftListClientCmd_S", Value=630)]
      RefreshAllGiftListClientCmd_S = 630,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickCommonGiftClientCmd_C", Value=631)]
      PickCommonGiftClientCmd_C = 631,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickMediaGiftClientCmd_C", Value=632)]
      PickMediaGiftClientCmd_C = 632,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultPickGiftClientCmd_S", Value=633)]
      ResultPickGiftClientCmd_S = 633,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateGiftStatusClientCmd_S", Value=634)]
      UpdateGiftStatusClientCmd_S = 634,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshOnlineGiftClientCmd_S", Value=635)]
      RefreshOnlineGiftClientCmd_S = 635,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshPhysicalGiftClientCmd_S", Value=636)]
      RefreshPhysicalGiftClientCmd_S = 636,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateActivityClientCmd_S", Value=637)]
      UpdateActivityClientCmd_S = 637,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateLoginDaysClientCmd_S", Value=638)]
      UpdateLoginDaysClientCmd_S = 638,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBuyFundClientCmd_C", Value=639)]
      ReqBuyFundClientCmd_C = 639,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondSignInOperatorClientCmd_S", Value=640)]
      RespondSignInOperatorClientCmd_S = 640,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSignInDataClientCmd_S", Value=641)]
      RefreshSignInDataClientCmd_S = 641,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignInClientCmd_C", Value=642)]
      SignInClientCmd_C = 642,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestViewPlayerInfoRankClientCmd_C", Value=648)]
      RequestViewPlayerInfoRankClientCmd_C = 648,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnViewPlayerInfoRankClientCmd_S", Value=649)]
      ReturnViewPlayerInfoRankClientCmd_S = 649,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestViewPlayerInfoClientCmd_C", Value=650)]
      RequestViewPlayerInfoClientCmd_C = 650,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnViewPlayerInfoClientCmd_S", Value=651)]
      ReturnViewPlayerInfoClientCmd_S = 651,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondFriendOperateClientCmd_S", Value=652)]
      RespondFriendOperateClientCmd_S = 652,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFriendListClientCmd_C", Value=653)]
      RequestFriendListClientCmd_C = 653,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshFriendListClientCmd_S", Value=654)]
      RefreshFriendListClientCmd_S = 654,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFriendDataClientCmd_S", Value=655)]
      UpdateFriendDataClientCmd_S = 655,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendInviteClientCmd_C", Value=656)]
      FriendInviteClientCmd_C = 656,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelFriendInviteClientCmd_C", Value=657)]
      CancelFriendInviteClientCmd_C = 657,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AgreeFriendApplyClientCmd_C", Value=658)]
      AgreeFriendApplyClientCmd_C = 658,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestDelFriendClientCmd_C", Value=659)]
      RequestDelFriendClientCmd_C = 659,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultDelFriendClientCmd_S", Value=660)]
      ResultDelFriendClientCmd_S = 660,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFriendInviteClientCmd_S", Value=661)]
      AddFriendInviteClientCmd_S = 661,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelFriendInviteClientCmd_S", Value=662)]
      DelFriendInviteClientCmd_S = 662,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFriendApplyClientCmd_S", Value=663)]
      AddFriendApplyClientCmd_S = 663,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelFriendApplyClientCmd_S", Value=664)]
      DelFriendApplyClientCmd_S = 664,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendOnlineClientCmd_S", Value=665)]
      FriendOnlineClientCmd_S = 665,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FindPlayerClientCmd_C", Value=666)]
      FindPlayerClientCmd_C = 666,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PresentGiftClientCmd_C", Value=668)]
      PresentGiftClientCmd_C = 668,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondSpriteOperateClientCmd_S", Value=670)]
      RespondSpriteOperateClientCmd_S = 670,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddGuardianClientCmd_C", Value=671)]
      AddGuardianClientCmd_C = 671,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveGuardianClientCmd_C", Value=672)]
      RemoveGuardianClientCmd_C = 672,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwapGuardianClientCmd_C", Value=673)]
      SwapGuardianClientCmd_C = 673,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSpriteListClientCmd_S", Value=674)]
      RefreshSpriteListClientCmd_S = 674,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateSpriteDataClientCmd_S", Value=675)]
      UpdateSpriteDataClientCmd_S = 675,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedSpriteClientCmd_C", Value=676)]
      FeedSpriteClientCmd_C = 676,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteFightClientCmd_C", Value=678)]
      SpriteFightClientCmd_C = 678,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PromoteQualityClientCmd_C", Value=679)]
      PromoteQualityClientCmd_C = 679,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AutoFeedSpriteClientCmd_C", Value=680)]
      AutoFeedSpriteClientCmd_C = 680,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshPetListClientCmd_S", Value=681)]
      RefreshPetListClientCmd_S = 681,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePetDataClientCmd_S", Value=682)]
      UpdatePetDataClientCmd_S = 682,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshDomesticationClientCmd_S", Value=683)]
      RefreshDomesticationClientCmd_S = 683,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SoulActiveClientCmd_C", Value=684)]
      SoulActiveClientCmd_C = 684,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DomesticateCleintCmd_C", Value=685)]
      DomesticateCleintCmd_C = 685,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PetPlayedClientCmd_C", Value=686)]
      PetPlayedClientCmd_C = 686,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangePetPlayedClientCmd_S", Value=687)]
      ChangePetPlayedClientCmd_S = 687,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeSoulClientCmd_S", Value=688)]
      ChangeSoulClientCmd_S = 688,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMarketOperateClientCmd_S", Value=700)]
      RespondMarketOperateClientCmd_S = 700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestMarketGoodsListClientCmd_C", Value=701)]
      RequestMarketGoodsListClientCmd_C = 701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnMarketGoodsListClientCmd_S", Value=702)]
      ReturnMarketGoodsListClientCmd_S = 702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestMyGoodsListClientCmd_C", Value=703)]
      RequestMyGoodsListClientCmd_C = 703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMyGoodsListClientCmd_S", Value=704)]
      RefreshMyGoodsListClientCmd_S = 704,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AuctionGoodsClientCmd_C", Value=705)]
      AuctionGoodsClientCmd_C = 705,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BidMarketGoodsClientCmd_C", Value=706)]
      BidMarketGoodsClientCmd_C = 706,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMarketSingleGoodsClientCmd_S", Value=707)]
      RefreshMarketSingleGoodsClientCmd_S = 707,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshPlayerFbDataClientCmd_S", Value=708)]
      RefreshPlayerFbDataClientCmd_S = 708,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerTransMapCmd_C", Value=709)]
      PlayerTransMapCmd_C = 709,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeClientCmd_S", Value=717)]
      RechargeClientCmd_S = 717,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdataFirstRechargeClientCmd_S", Value=718)]
      UpdataFirstRechargeClientCmd_S = 718,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshAchievementListClientCmd_S", Value=720)]
      RefreshAchievementListClientCmd_S = 720,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateDoingAchievementDataClientCmd_S", Value=721)]
      UpdateDoingAchievementDataClientCmd_S = 721,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFinishAchievementClientCmd_S", Value=722)]
      AddFinishAchievementClientCmd_S = 722,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TakenAchievementRewardClientCmd_C", Value=723)]
      TakenAchievementRewardClientCmd_C = 723,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultTakenAchievementRewardClientCmd_S", Value=724)]
      ResultTakenAchievementRewardClientCmd_S = 724,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMyReputationClientCmd_S", Value=740)]
      RefreshMyReputationClientCmd_S = 740,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReputationExchangeItemClientCmd_C", Value=741)]
      ReputationExchangeItemClientCmd_C = 741,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondExchangeItemClientCmd_S", Value=742)]
      RespondExchangeItemClientCmd_S = 742,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshTitleListClientCmd_S", Value=750)]
      RefreshTitleListClientCmd_S = 750,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeCurTitleClientCmd_C", Value=751)]
      ChangeCurTitleClientCmd_C = 751,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultChangeCurTitleClientCmd_S", Value=752)]
      ResultChangeCurTitleClientCmd_S = 752,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddTitleClientCmd_S", Value=753)]
      AddTitleClientCmd_S = 753,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerJumpMoveClientCmd_S", Value=754)]
      PlayerJumpMoveClientCmd_S = 754,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMonsterOrganizeClientCmd_S", Value=780)]
      SendMonsterOrganizeClientCmd_S = 780,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMonsterDataFinishClientCmd_S", Value=781)]
      SendMonsterDataFinishClientCmd_S = 781,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendLoadedSceneClientCmd_C", Value=782)]
      SendLoadedSceneClientCmd_C = 782,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestJoinTeamClientCmd_C", Value=783)]
      RequestJoinTeamClientCmd_C = 783,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KillAllMonsterClientCmd_C", Value=784)]
      KillAllMonsterClientCmd_C = 784,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendReadyClientCmd_CS", Value=785)]
      SendReadyClientCmd_CS = 785,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KillAllEnemyClientCmd_C", Value=786)]
      KillAllEnemyClientCmd_C = 786,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPlayerDataFinishClientCmd_S", Value=787)]
      SendPlayerDataFinishClientCmd_S = 787,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateArenaSortClientCmd_S", Value=792)]
      UpdateArenaSortClientCmd_S = 792,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetArenaSortClientCmd_C", Value=793)]
      GetArenaSortClientCmd_C = 793,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LeftArenaFbClientCmd_C", Value=794)]
      LeftArenaFbClientCmd_C = 794,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArenaWinClientCmd_C", Value=795)]
      ArenaWinClientCmd_C = 795,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateGiveArenaNumClientCmd_S", Value=798)]
      UpdateGiveArenaNumClientCmd_S = 798,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFriendArenaSortClientCmd_S", Value=802)]
      UpdateFriendArenaSortClientCmd_S = 802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestReliveClientCmd_C", Value=803)]
      RequestReliveClientCmd_C = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RelivePlayerDeathClienCmd_S", Value=804)]
      RelivePlayerDeathClienCmd_S = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyPhysicalClientCmd_C", Value=805)]
      BuyPhysicalClientCmd_C = 805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyGameMoneyClientCmd_C", Value=806)]
      BuyGameMoneyClientCmd_C = 806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyGameMoneyClientCmd_S", Value=807)]
      BuyGameMoneyClientCmd_S = 807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RelivePlayerFailClientCmd_S", Value=808)]
      RelivePlayerFailClientCmd_S = 808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetDailyListClientCmd_C", Value=810)]
      GetDailyListClientCmd_C = 810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateDailyList_S", Value=811)]
      UpdateDailyList_S = 811,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetDailyAwardClientCmd_C", Value=812)]
      GetDailyAwardClientCmd_C = 812,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendWitchTip_S", Value=813)]
      SendWitchTip_S = 813,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetWitchTipClientCmd_C", Value=814)]
      GetWitchTipClientCmd_C = 814,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GreedClientCmd_C", Value=815)]
      GreedClientCmd_C = 815,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetActiveBoxClientCmd_C", Value=816)]
      GetActiveBoxClientCmd_C = 816,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondRuneOperateClientCmd_S", Value=820)]
      RespondRuneOperateClientCmd_S = 820,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshAllRuneDataClientCmd_S", Value=821)]
      RefreshAllRuneDataClientCmd_S = 821,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PrayClientCmd_C", Value=822)]
      PrayClientCmd_C = 822,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultPrayClientCmd_S", Value=823)]
      ResultPrayClientCmd_S = 823,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeRuneTransformLevelClientCmd_CS", Value=824)]
      ChangeRuneTransformLevelClientCmd_CS = 824,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRuneChipNumClientCmd_S", Value=826)]
      UpdateRuneChipNumClientCmd_S = 826,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRuneDataClientCmd_S", Value=828)]
      UpdateRuneDataClientCmd_S = 828,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveRuneClientCmd_S", Value=829)]
      RemoveRuneClientCmd_S = 829,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MarkRuneClientCmd_C", Value=830)]
      MarkRuneClientCmd_C = 830,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MarkRuneAdvanceClientCmd_C", Value=831)]
      MarkRuneAdvanceClientCmd_C = 831,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RuneAdvanceClientCmd_C", Value=832)]
      RuneAdvanceClientCmd_C = 832,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TransformRuneClientCmd_C", Value=833)]
      TransformRuneClientCmd_C = 833,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TakeOutRuneClientCmd_C", Value=834)]
      TakeOutRuneClientCmd_C = 834,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateIntellClientCmd_S", Value=839)]
      UpdateIntellClientCmd_S = 839,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateMarkRuneDataClientCmd_S", Value=840)]
      UpdateMarkRuneDataClientCmd_S = 840,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshRuneLinkAttrClientCmd_S", Value=841)]
      RefreshRuneLinkAttrClientCmd_S = 841,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PraiseClientCmd_C", Value=850)]
      PraiseClientCmd_C = 850,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateNewsDataClientCmd_S", Value=851)]
      UpdateNewsDataClientCmd_S = 851,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeleteNewsClientCmd_S", Value=852)]
      DeleteNewsClientCmd_S = 852,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestRecommendFriendClientCmd_C", Value=853)]
      RequestRecommendFriendClientCmd_C = 853,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshRecommendFriendClientCmd_S", Value=854)]
      RefreshRecommendFriendClientCmd_S = 854,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelRecommendFriendClientCmd_S", Value=855)]
      DelRecommendFriendClientCmd_S = 855,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSetAttrCmd_C", Value=900)]
      ReqSetAttrCmd_C = 900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSetAttrCmd_S", Value=901)]
      RspSetAttrCmd_S = 901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetAttrCmd_C", Value=902)]
      ReqGetAttrCmd_C = 902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetAttrCmd_S", Value=903)]
      RspGetAttrCmd_S = 903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQueryTopCmd_C", Value=911)]
      ReqQueryTopCmd_C = 911,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQueryTopCmd_S", Value=912)]
      RspQueryTopCmd_S = 912,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQueryRandomCmd_C", Value=913)]
      ReqQueryRandomCmd_C = 913,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQueryRandomCmd_S", Value=914)]
      RspQueryRandomCmd_S = 914,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqInitPvAiCmd_C", Value=915)]
      ReqInitPvAiCmd_C = 915,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspInitPvAiCmd_S", Value=916)]
      RspInitPvAiCmd_S = 916,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStartPvAiCmd_C", Value=917)]
      ReqStartPvAiCmd_C = 917,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspStartPvAiCmd_S", Value=918)]
      RspStartPvAiCmd_S = 918,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSwapRankCmd_C", Value=919)]
      ReqSwapRankCmd_C = 919,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSwapRankCmd_S", Value=920)]
      RspSwapRankCmd_S = 920,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFreeQueryPlayerCmd_C", Value=921)]
      ReqFreeQueryPlayerCmd_C = 921,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQuerySelfCmd_C", Value=922)]
      ReqQuerySelfCmd_C = 922,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQuerySelfCmd_S", Value=923)]
      RspQuerySelfCmd_S = 923,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqClearPVAICdCmd_C", Value=924)]
      ReqClearPVAICdCmd_C = 924,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspClearPVAICdCmd_S", Value=925)]
      RspClearPVAICdCmd_S = 925,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQueryFightRandomCmd_C", Value=926)]
      ReqQueryFightRandomCmd_C = 926,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQueryFightRandomCmd_S", Value=927)]
      RspQueryFightRandomCmd_S = 927,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqVipRightsBuyCmd_C", Value=928)]
      ReqVipRightsBuyCmd_C = 928,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspVipRightsBuyCmd_S", Value=929)]
      RspVipRightsBuyCmd_S = 929,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetPVAIFightCDCmd_C", Value=930)]
      ReqGetPVAIFightCDCmd_C = 930,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetPVAIFightCDCmd_S", Value=931)]
      RspGetPVAIFightCDCmd_S = 931,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTopRankCmd_C", Value=932)]
      ReqTopRankCmd_C = 932,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspTopRankCmd_S", Value=933)]
      RspTopRankCmd_S = 933,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPvAiFightLog_C", Value=934)]
      ReqPvAiFightLog_C = 934,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RsqPvAiFightLog_S", Value=935)]
      RsqPvAiFightLog_S = 935,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAILoginCmd_C", Value=940)]
      ReqAILoginCmd_C = 940,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshTreasureListClientCmd_S", Value=950)]
      RefreshTreasureListClientCmd_S = 950,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DonateTreasureClientCmd_C", Value=951)]
      DonateTreasureClientCmd_C = 951,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddTreasureClientCmd_S", Value=952)]
      AddTreasureClientCmd_S = 952,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelTreasureClientCmd_S", Value=953)]
      DelTreasureClientCmd_S = 953,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IdentifyTreasureClientCmd_C", Value=954)]
      IdentifyTreasureClientCmd_C = 954,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddIdentifyRecordClientCmd_S", Value=955)]
      AddIdentifyRecordClientCmd_S = 955,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRefreshCompassClientCmd_C", Value=1000)]
      ReqRefreshCompassClientCmd_C = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRefreshCompassClientCmd_S", Value=1001)]
      RspRefreshCompassClientCmd_S = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCompassLotteryClientCmd_C", Value=1002)]
      ReqCompassLotteryClientCmd_C = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCompassLotteryClientCmd_S", Value=1003)]
      RspCompassLotteryClientCmd_S = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendCompassItemsClientCmd_S", Value=1004)]
      SendCompassItemsClientCmd_S = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTreasureChestLotteryClientCmd_C", Value=1010)]
      ReqTreasureChestLotteryClientCmd_C = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspTreasureChestLotteryClientCmd_S", Value=1011)]
      RspTreasureChestLotteryClientCmd_S = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendTreasureChestInfoClientCmd_S", Value=1012)]
      SendTreasureChestInfoClientCmd_S = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspWorldBossHpCmd_S", Value=1020)]
      RspWorldBossHpCmd_S = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspWBossHurtCmd_S", Value=1021)]
      RspWBossHurtCmd_S = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGBossHurtCmd_S", Value=1022)]
      RspGBossHurtCmd_S = 1022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCreateWipeFbClientCmd_C", Value=1050)]
      ReqCreateWipeFbClientCmd_C = 1050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyPhysicalClientCmd_S", Value=1051)]
      BuyPhysicalClientCmd_S = 1051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddPlayerCmd_S", Value=1052)]
      RspAddPlayerCmd_S = 1052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRemovePlayerCmd_S", Value=1053)]
      RspRemovePlayerCmd_S = 1053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPlatLoginCmd_S", Value=1054)]
      RspPlatLoginCmd_S = 1054,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspNotifyActivityCmd_S", Value=1055)]
      RspNotifyActivityCmd_S = 1055,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqInitPVECmd_C", Value=1056)]
      ReqInitPVECmd_C = 1056,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStartPVECmd_C", Value=1057)]
      ReqStartPVECmd_C = 1057,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspInitPVECmd_S", Value=1058)]
      RspInitPVECmd_S = 1058,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendAllCardsClientCmd_S", Value=1060)]
      SendAllCardsClientCmd_S = 1060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendAllSpreadsClientCmd_S", Value=1061)]
      SendAllSpreadsClientCmd_S = 1061,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCallCardClientCmd_C", Value=1062)]
      ReqCallCardClientCmd_C = 1062,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLoadCardClientCmd_C", Value=1063)]
      ReqLoadCardClientCmd_C = 1063,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUnloadCardClientCmd_C", Value=1064)]
      ReqUnloadCardClientCmd_C = 1064,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUpgradeCardClientCmd_C", Value=1065)]
      ReqUpgradeCardClientCmd_C = 1065,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqWashCardEdgeClientCmd_C", Value=1066)]
      ReqWashCardEdgeClientCmd_C = 1066,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLoadSkillClientCmd_C", Value=1067)]
      ReqLoadSkillClientCmd_C = 1067,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCallCardClientCmd_S", Value=1068)]
      RspCallCardClientCmd_S = 1068,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLoadCardClientCmd_S", Value=1069)]
      RspLoadCardClientCmd_S = 1069,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspUpgradeCardClientCmd_S", Value=1070)]
      RspUpgradeCardClientCmd_S = 1070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspWashCardEdgeClientCmd_S", Value=1071)]
      RspWashCardEdgeClientCmd_S = 1071,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLoadSkillClientCmd_S", Value=1072)]
      RspLoadSkillClientCmd_S = 1072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspUnloadCardClientCmd_S", Value=1073)]
      RspUnloadCardClientCmd_S = 1073,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendSpreadAttrClientCmd_S", Value=1074)]
      SendSpreadAttrClientCmd_S = 1074,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DropCardClientCmd_S", Value=1075)]
      DropCardClientCmd_S = 1075,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendLeftFreeWashEdgeNumClientCmd_S", Value=1076)]
      SendLeftFreeWashEdgeNumClientCmd_S = 1076,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPsychicDrawCardClientCmd_C", Value=1081)]
      ReqPsychicDrawCardClientCmd_C = 1081,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPsychicDrawCardsClientCmd_S", Value=1077)]
      SendPsychicDrawCardsClientCmd_S = 1077,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendCancelDrawCardCDTime_CS", Value=1078)]
      SendCancelDrawCardCDTime_CS = 1078,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPsychicTurnCard_C", Value=1079)]
      ReqPsychicTurnCard_C = 1079,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPsychicTurnCard_S", Value=1080)]
      SendPsychicTurnCard_S = 1080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendDrawCardCountDown_S", Value=1082)]
      SendDrawCardCountDown_S = 1082,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPsychicChallengeClientCmd_C", Value=1083)]
      ReqPsychicChallengeClientCmd_C = 1083,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPsychicChallengeRemainCountClientCmd_S", Value=1084)]
      SendPsychicChallengeRemainCountClientCmd_S = 1084,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSpiritStoneListClientCmd_S", Value=1200)]
      RefreshSpiritStoneListClientCmd_S = 1200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateSpiritStoneDataClientCmd_S", Value=1201)]
      UpdateSpiritStoneDataClientCmd_S = 1201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelSpiritStoneClientCmd_S", Value=1202)]
      DelSpiritStoneClientCmd_S = 1202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReformSpiritStoneClientCmd_C", Value=1203)]
      ReformSpiritStoneClientCmd_C = 1203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReformSpiritStoneResultClientCmd_S", Value=1204)]
      ReformSpiritStoneResultClientCmd_S = 1204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpiritStoneRevertClientCmd_C", Value=1205)]
      SpiritStoneRevertClientCmd_C = 1205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EmbedSpiritStoneClientCmd_C", Value=1206)]
      EmbedSpiritStoneClientCmd_C = 1206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TakeOutSpiritStoneClientCmd_C", Value=1207)]
      TakeOutSpiritStoneClientCmd_C = 1207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpiritStoneUpgradeClientCmd_C", Value=1208)]
      SpiritStoneUpgradeClientCmd_C = 1208,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqWingUnLockCmd_C", Value=1220)]
      ReqWingUnLockCmd_C = 1220,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspWingUnLockCmd_S", Value=1221)]
      RspWingUnLockCmd_S = 1221,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestRelivePlayerDeathReliveClientCmd_C", Value=1230)]
      RequestRelivePlayerDeathReliveClientCmd_C = 1230,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueryResearchListClientCmd_C", Value=1240)]
      QueryResearchListClientCmd_C = 1240,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendResearchListClientCmd_S", Value=1241)]
      SendResearchListClientCmd_S = 1241,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMyGeneResearchClientCmd_S", Value=1242)]
      SendMyGeneResearchClientCmd_S = 1242,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBeginResearchClientCmd_C", Value=1243)]
      ReqBeginResearchClientCmd_C = 1243,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRobGeneResearchClientCmd_C", Value=1244)]
      ReqRobGeneResearchClientCmd_C = 1244,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGeneResearchAwardTakeClientCmd_C", Value=1245)]
      ReqGeneResearchAwardTakeClientCmd_C = 1245,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendGeneResearchRobLogClientCmd_S", Value=1246)]
      SendGeneResearchRobLogClientCmd_S = 1246,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSignUpCmd_C", Value=1260)]
      ReqSignUpCmd_C = 1260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSignUpCmd_S", Value=1261)]
      RspSignUpCmd_S = 1261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetGuildStrongHoldCmd_C", Value=1264)]
      ReqGetGuildStrongHoldCmd_C = 1264,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetGuildStrongHoldCmd_S", Value=1265)]
      RspGetGuildStrongHoldCmd_S = 1265,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspStrongHoldInfoCmd_S", Value=1266)]
      RspStrongHoldInfoCmd_S = 1266,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGuildFbStateCmd_S", Value=1267)]
      RspGuildFbStateCmd_S = 1267,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqJoinStrongHoldCmd_C", Value=1268)]
      ReqJoinStrongHoldCmd_C = 1268,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFightStrongHoldCmd_C", Value=1269)]
      ReqFightStrongHoldCmd_C = 1269,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGenMineCmd_C", Value=1270)]
      ReqGenMineCmd_C = 1270,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGenMineCmd_S", Value=1271)]
      RspGenMineCmd_S = 1271,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetAttackedStrongHoldTimeCmd_S", Value=1272)]
      RspGetAttackedStrongHoldTimeCmd_S = 1272,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspNotifyAttackedCmd_S", Value=1273)]
      RspNotifyAttackedCmd_S = 1273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetOpponentInfoCmd_C", Value=1280)]
      ReqGetOpponentInfoCmd_C = 1280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetOpponentInfoCmd_S", Value=1281)]
      RspGetOpponentInfoCmd_S = 1281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspNotifyWarTimeCmd_S", Value=1282)]
      RspNotifyWarTimeCmd_S = 1282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuildWarRankCmd_C", Value=1283)]
      ReqGuildWarRankCmd_C = 1283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGuildWarRankCmd_S", Value=1284)]
      RspGuildWarRankCmd_S = 1284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuildWarSetReadyCmd_C", Value=1285)]
      ReqGuildWarSetReadyCmd_C = 1285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGuildWarSetReadyCmd_S", Value=1286)]
      RspGuildWarSetReadyCmd_S = 1286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetGuildGroupDataCmd_C", Value=1287)]
      ReqGetGuildGroupDataCmd_C = 1287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetGuildGroupDataCmd_S", Value=1288)]
      RspGetGuildGroupDataCmd_S = 1288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendInfoMRankClientCmd_S", Value=1300)]
      SendInfoMRankClientCmd_S = 1300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTrainMRankClientCmd_C", Value=1301)]
      ReqTrainMRankClientCmd_C = 1301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPromoteMRankClientCmd_C", Value=1302)]
      ReqPromoteMRankClientCmd_C = 1302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspTrainMRankClientCmd_S", Value=1303)]
      RspTrainMRankClientCmd_S = 1303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshAllActivityListClientCmd_S", Value=1321)]
      RefreshAllActivityListClientCmd_S = 1321,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateActivityDataClientCmd_S", Value=1322)]
      UpdateActivityDataClientCmd_S = 1322,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TakeActivityRewardClientCmd_C", Value=1323)]
      TakeActivityRewardClientCmd_C = 1323,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelActivityListClientCmd_S", Value=1324)]
      DelActivityListClientCmd_S = 1324,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetFbStateCmd_C", Value=1341)]
      ReqGetFbStateCmd_C = 1341,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetFbStateCmd_S", Value=1342)]
      RspGetFbStateCmd_S = 1342,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshRewardListClientCmd_S", Value=1350)]
      RefreshRewardListClientCmd_S = 1350,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TakeRewardClientCmd_C", Value=1351)]
      TakeRewardClientCmd_C = 1351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelRewardClientCmd_S", Value=1352)]
      DelRewardClientCmd_S = 1352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateRewardDataClientCmd_S", Value=1353)]
      UpdateRewardDataClientCmd_S = 1353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshLotteryRankingListClientCmd_S", Value=1360)]
      RefreshLotteryRankingListClientCmd_S = 1360,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateJackpotClientCmd_S", Value=1361)]
      UpdateJackpotClientCmd_S = 1361,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateMyLotteryCountClientCmd_S", Value=1362)]
      UpdateMyLotteryCountClientCmd_S = 1362,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshScratchRecordClientCmd_S", Value=1363)]
      RefreshScratchRecordClientCmd_S = 1363,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ScratchClientCmd_C", Value=1364)]
      ScratchClientCmd_C = 1364,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ScratchResultCliemtCmd_S", Value=1365)]
      ScratchResultCliemtCmd_S = 1365,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshLotteryRewardClientCmd_S", Value=1366)]
      RefreshLotteryRewardClientCmd_S = 1366,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TakeLotteryRewardClientCmd_C", Value=1367)]
      TakeLotteryRewardClientCmd_C = 1367,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLotteryRankingListClientCmd_C", Value=1368)]
      ReqLotteryRankingListClientCmd_C = 1368,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCreateRoomCmd_C", Value=1401)]
      ReqCreateRoomCmd_C = 1401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqJoinRoomCmd_C", Value=1402)]
      ReqJoinRoomCmd_C = 1402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqForceLeaveCmd_C", Value=1403)]
      ReqForceLeaveCmd_C = 1403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqReadyCmd_C", Value=1404)]
      ReqReadyCmd_C = 1404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSyncRoomCmd_S", Value=1405)]
      RspSyncRoomCmd_S = 1405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetRoomListCmd_C", Value=1406)]
      ReqGetRoomListCmd_C = 1406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetRoomListCmd_S", Value=1407)]
      RspGetRoomListCmd_S = 1407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStartRoomCmd_C", Value=1408)]
      ReqStartRoomCmd_C = 1408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCloseRoomCmd_S", Value=1409)]
      RspCloseRoomCmd_S = 1409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCreateRoomCmd_S", Value=1410)]
      RspCreateRoomCmd_S = 1410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspStartRoomCmd_S", Value=1411)]
      RspStartRoomCmd_S = 1411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCancelRoomCmd_S", Value=1412)]
      RspCancelRoomCmd_S = 1412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqKickMemberCmd_C", Value=1413)]
      ReqKickMemberCmd_C = 1413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetAllStrongHoldInfoCmd_C", Value=1451)]
      ReqGetAllStrongHoldInfoCmd_C = 1451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetAllStrongHoldInfoCmd_S", Value=1452)]
      RspGetAllStrongHoldInfoCmd_S = 1452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStrongHoldSupportCmd_C", Value=1453)]
      ReqStrongHoldSupportCmd_C = 1453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStrongHoldGiveUpCmd_C", Value=1454)]
      ReqStrongHoldGiveUpCmd_C = 1454,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStrongHoldAttackedCmd_C", Value=1455)]
      ReqStrongHoldAttackedCmd_C = 1455,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetGuildAttrCmd_C", Value=1456)]
      ReqGetGuildAttrCmd_C = 1456,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetGuildAttrCmd_S", Value=1457)]
      RspGetGuildAttrCmd_S = 1457,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspStrongHoldSupportCmd_S", Value=1458)]
      RspStrongHoldSupportCmd_S = 1458,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspStrongHoldGiveUpCmd_S", Value=1459)]
      RspStrongHoldGiveUpCmd_S = 1459,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspStrongHoldRatioCmd_S", Value=1460)]
      RspStrongHoldRatioCmd_S = 1460,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSetGuildAttrCmd_C", Value=1461)]
      ReqSetGuildAttrCmd_C = 1461,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendOtherWorldTransmitCmd_S", Value=1600)]
      SendOtherWorldTransmitCmd_S = 1600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendOtherWorldTransmitDestoryCmd_S", Value=1601)]
      SendOtherWorldTransmitDestoryCmd_S = 1601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqInvitePVPCmd_C", Value=1610)]
      ReqInvitePVPCmd_C = 1610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspInvitePVPCmd_S", Value=1611)]
      RspInvitePVPCmd_S = 1611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqWorldBossHurtRankCmd_C", Value=1620)]
      ReqWorldBossHurtRankCmd_C = 1620,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspWorldBossHurtRankCmd_S", Value=1621)]
      RspWorldBossHurtRankCmd_S = 1621,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelSuspendGmClientCmd_C", Value=5000)]
      ReqDelSuspendGmClientCmd_C = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelSuspendGmClientCmd_S", Value=5001)]
      RspDelSuspendGmClientCmd_S = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelNoticeGmClientCmd_C", Value=5002)]
      ReqDelNoticeGmClientCmd_C = 5002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelNoticeGmClientCmd_S", Value=5003)]
      RspDelNoticeGmClientCmd_S = 5003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUserLoginGmClientCmd_C", Value=5004)]
      ReqUserLoginGmClientCmd_C = 5004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspUserLoginGmClientCmd_S", Value=5005)]
      RspUserLoginGmClientCmd_S = 5005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspConnectGmClientCmd_S", Value=5006)]
      RspConnectGmClientCmd_S = 5006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindPlayerGmClientCmd_C", Value=5007)]
      ReqFindPlayerGmClientCmd_C = 5007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindPlayerGmClientCmd_S", Value=5008)]
      RspFindPlayerGmClientCmd_S = 5008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindPlayerListGmClientCmd_C", Value=5009)]
      ReqFindPlayerListGmClientCmd_C = 5009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindPlayerListGmClientCmd_S", Value=5010)]
      RspFindPlayerListGmClientCmd_S = 5010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindSuspendGmClientCmd_C", Value=5011)]
      ReqFindSuspendGmClientCmd_C = 5011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindSuspendGmClientCmd_S", Value=5012)]
      RspFindSuspendGmClientCmd_S = 5012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddSuspendGmClientCmd_C", Value=5013)]
      ReqAddSuspendGmClientCmd_C = 5013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddSuspendGmClientCmd_S", Value=5014)]
      RspAddSuspendGmClientCmd_S = 5014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindNoticeGmClientCmd_C", Value=5015)]
      ReqFindNoticeGmClientCmd_C = 5015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindNoticeGmClientCmd_S", Value=5016)]
      RspFindNoticeGmClientCmd_S = 5016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddNoticeGmClientCmd_C", Value=5017)]
      ReqAddNoticeGmClientCmd_C = 5017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddNoticeGmClientCmd_S", Value=5018)]
      RspAddNoticeGmClientCmd_S = 5018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqReloadGmServerGmClientCmd_C", Value=5019)]
      ReqReloadGmServerGmClientCmd_C = 5019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddActivityGmClientCmd_C", Value=5021)]
      ReqAddActivityGmClientCmd_C = 5021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddActivityGmClientCmd_S", Value=5022)]
      RspAddActivityGmClientCmd_S = 5022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelActivityGmClientCmd_C", Value=5023)]
      ReqDelActivityGmClientCmd_C = 5023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelActivityGmClientCmd_S", Value=5024)]
      RspDelActivityGmClientCmd_S = 5024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqActivityListGmClientCmd_C", Value=5025)]
      ReqActivityListGmClientCmd_C = 5025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspActivityListGmClientCmd_S", Value=5026)]
      RspActivityListGmClientCmd_S = 5026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqViewActivityGmClientCmd_C", Value=5027)]
      ReqViewActivityGmClientCmd_C = 5027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspViewActivityGmClientCmd_S", Value=5028)]
      RspViewActivityGmClientCmd_S = 5028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGmCommandGmClientCmd_C", Value=5030)]
      ReqGmCommandGmClientCmd_C = 5030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGmCommandGmClientCmd_S", Value=5031)]
      RspGmCommandGmClientCmd_S = 5031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSendMailGmClientCmd_C", Value=5032)]
      ReqSendMailGmClientCmd_C = 5032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSendMailGmClientCmd_S", Value=5033)]
      RspSendMailGmClientCmd_S = 5033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddGmAccountGmClientCmd_C", Value=5035)]
      ReqAddGmAccountGmClientCmd_C = 5035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddGmAccountGmClientCmd_S", Value=5036)]
      RspAddGmAccountGmClientCmd_S = 5036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqModGmAccountGmClientCmd_C", Value=5037)]
      ReqModGmAccountGmClientCmd_C = 5037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspModGmAccountGmClientCmd_S", Value=5038)]
      RspModGmAccountGmClientCmd_S = 5038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindGmAccountGmClientCmd_C", Value=5039)]
      ReqFindGmAccountGmClientCmd_C = 5039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindGmAccountGmClientCmd_S", Value=5040)]
      RspFindGmAccountGmClientCmd_S = 5040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqModGmAccountPasswdGmClientCmd_C", Value=5041)]
      ReqModGmAccountPasswdGmClientCmd_C = 5041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendServerInfoGmClientCmd_S", Value=5042)]
      SendServerInfoGmClientCmd_S = 5042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindGmLogGmClientCmd_C", Value=5043)]
      ReqFindGmLogGmClientCmd_C = 5043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindGmLogGmClientCmd_S", Value=5044)]
      RspFindGmLogGmClientCmd_S = 5044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspErrorGmClientCmd_S", Value=5045)]
      RspErrorGmClientCmd_S = 5045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddRewardGmClientCmd_C", Value=5046)]
      ReqAddRewardGmClientCmd_C = 5046,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddRewardGmClientCmd_S", Value=5047)]
      RspAddRewardGmClientCmd_S = 5047,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelRewardGmClientCmd_C", Value=5048)]
      ReqDelRewardGmClientCmd_C = 5048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelRewardGmClientCmd_S", Value=5049)]
      RspDelRewardGmClientCmd_S = 5049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRewardListGmClientCmd_C", Value=5050)]
      ReqRewardListGmClientCmd_C = 5050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRewardListGmClientCmd_S", Value=5051)]
      RspRewardListGmClientCmd_S = 5051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRankListClientCmd_C", Value=5052)]
      ReqRankListClientCmd_C = 5052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPVAIRankListClientCmd_S", Value=5053)]
      RspPVAIRankListClientCmd_S = 5053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFightRankListClientCmd_S", Value=5054)]
      RspFightRankListClientCmd_S = 5054,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSTATOperateGmClientCmd_C", Value=5055)]
      ReqSTATOperateGmClientCmd_C = 5055,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSTATOperateGmClientCmd_S", Value=5056)]
      RspSTATOperateGmClientCmd_S = 5056,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelPlayerItemGmClientCmd_CS", Value=5057)]
      ReqDelPlayerItemGmClientCmd_CS = 5057,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPlayerDelItemTodoGmClientCmd_CS", Value=5058)]
      ReqPlayerDelItemTodoGmClientCmd_CS = 5058,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCancelDelItemTodoGmClientCmd_C", Value=5059)]
      ReqCancelDelItemTodoGmClientCmd_C = 5059,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCancelDelItemTodoGmClientCmd_S", Value=5060)]
      RspCancelDelItemTodoGmClientCmd_S = 5060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRedirectCsGmClientCmd_C", Value=5061)]
      ReqRedirectCsGmClientCmd_C = 5061
    }
  
}