//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GmErrorCode.proto
namespace ProtoCmd
{
    [global::ProtoBuf.ProtoContract(Name=@"GmErrorCode")]
    public enum GmErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_SUCCESS", Value=0)]
      GMERR_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_UNKNOWN", Value=1)]
      GMERR_UNKNOWN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_GMACCOUNT_NORIGHT", Value=2)]
      GMERR_GMACCOUNT_NORIGHT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_GMACCOUNT_EXISTED", Value=10)]
      GMERR_GMACCOUNT_EXISTED = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_GMACCOUNT_NOTEXISTED", Value=11)]
      GMERR_GMACCOUNT_NOTEXISTED = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_GMACCOUNT_WRONGPASSWD", Value=12)]
      GMERR_GMACCOUNT_WRONGPASSWD = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_GMACCOUNT_BAN", Value=13)]
      GMERR_GMACCOUNT_BAN = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_ACTIVITY_EXISTED", Value=20)]
      GMERR_ACTIVITY_EXISTED = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_ACTIVITY_NOTEXISTED", Value=21)]
      GMERR_ACTIVITY_NOTEXISTED = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_UNKNOWN_RANKTYPE", Value=30)]
      GMERR_UNKNOWN_RANKTYPE = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_NOTFIND_EVENT", Value=40)]
      GMERR_NOTFIND_EVENT = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMERR_DEL_FAIL", Value=41)]
      GMERR_DEL_FAIL = 41
    }
  
}