//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GmToolDefine.proto
// Note: requires additional types generated from: ActivityDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmPlayerBaseData")]
  public partial class GmPlayerBaseData : global::ProtoBuf.IExtensible
  {
    public GmPlayerBaseData() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _account = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] account
    {
      get { return _account; }
      set { _account = value; }
    }
    private uint _career = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint career
    {
      get { return _career; }
      set { _career = value; }
    }
    private bool _online = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private uint _lasttime = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lasttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lasttime
    {
      get { return _lasttime; }
      set { _lasttime = value; }
    }
    private uint _lev = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lev
    {
      get { return _lev; }
      set { _lev = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private uint _physical = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"physical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint physical
    {
      get { return _physical; }
      set { _physical = value; }
    }
    private uint _createtime = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }
    private byte[] _guild = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"guild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] guild
    {
      get { return _guild; }
      set { _guild = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmPlayerViewItem")]
  public partial class GmPlayerViewItem : global::ProtoBuf.IExtensible
  {
    public GmPlayerViewItem() {}
    
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _pack = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pack
    {
      get { return _pack; }
      set { _pack = value; }
    }
    private uint _eventid = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"eventid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventid
    {
      get { return _eventid; }
      set { _eventid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmNoticeCondition")]
  public partial class GmNoticeCondition : global::ProtoBuf.IExtensible
  {
    public GmNoticeCondition() {}
    
    private uint _srvid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"srvid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint srvid
    {
      get { return _srvid; }
      set { _srvid = value; }
    }
    private byte[] _notice = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private uint _begtime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"begtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint begtime
    {
      get { return _begtime; }
      set { _begtime = value; }
    }
    private uint _endtime = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint endtime
    {
      get { return _endtime; }
      set { _endtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmNoticeData")]
  public partial class GmNoticeData : global::ProtoBuf.IExtensible
  {
    public GmNoticeData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _notice = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _sendtimes = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sendtimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sendtimes
    {
      get { return _sendtimes; }
      set { _sendtimes = value; }
    }
    private uint _begtime = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"begtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint begtime
    {
      get { return _begtime; }
      set { _begtime = value; }
    }
    private uint _createtime = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }
    private uint _interval = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"interval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint interval
    {
      get { return _interval; }
      set { _interval = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmAccountData")]
  public partial class GmAccountData : global::ProtoBuf.IExtensible
  {
    public GmAccountData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _grade = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private uint _optypes = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"optypes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint optypes
    {
      get { return _optypes; }
      set { _optypes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmLogCondition")]
  public partial class GmLogCondition : global::ProtoBuf.IExtensible
  {
    public GmLogCondition() {}
    
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _begtime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"begtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint begtime
    {
      get { return _begtime; }
      set { _begtime = value; }
    }
    private uint _endtime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint endtime
    {
      get { return _endtime; }
      set { _endtime = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmLogData")]
  public partial class GmLogData : global::ProtoBuf.IExtensible
  {
    public GmLogData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _subtype = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint subtype
    {
      get { return _subtype; }
      set { _subtype = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private byte[] _account = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] account
    {
      get { return _account; }
      set { _account = value; }
    }
    private byte[] _content = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private byte[] _remark = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private byte[] _ip = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private byte[] _attachment = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"attachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] attachment
    {
      get { return _attachment; }
      set { _attachment = value; }
    }
    private byte[] _server = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] server
    {
      get { return _server; }
      set { _server = value; }
    }
    private uint _ret = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmSuspendData")]
  public partial class GmSuspendData : global::ProtoBuf.IExtensible
  {
    public GmSuspendData() {}
    
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _career = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint career
    {
      get { return _career; }
      set { _career = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private byte[] _remark = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"remark", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] remark
    {
      get { return _remark; }
      set { _remark = value; }
    }
    private ulong _endtime = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong endtime
    {
      get { return _endtime; }
      set { _endtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmServerInfo")]
  public partial class GmServerInfo : global::ProtoBuf.IExtensible
  {
    public GmServerInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmActivityBaseData")]
  public partial class GmActivityBaseData : global::ProtoBuf.IExtensible
  {
    public GmActivityBaseData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmActivityFinCond")]
  public partial class GmActivityFinCond : global::ProtoBuf.IExtensible
  {
    public GmActivityFinCond() {}
    
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private uint _valuetype = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"valuetype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint valuetype
    {
      get { return _valuetype; }
      set { _valuetype = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item
    {
      get { return _item; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.ActivityRewardData> _reward = new global::System.Collections.Generic.List<ProtoCmd.ActivityRewardData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ActivityRewardData> reward
    {
      get { return _reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmActivityData")]
  public partial class GmActivityData : global::ProtoBuf.IExtensible
  {
    public GmActivityData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _showtime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"showtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint showtime
    {
      get { return _showtime; }
      set { _showtime = value; }
    }
    private uint _begtime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"begtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint begtime
    {
      get { return _begtime; }
      set { _begtime = value; }
    }
    private uint _endtime = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint endtime
    {
      get { return _endtime; }
      set { _endtime = value; }
    }
    private uint _distime = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"distime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint distime
    {
      get { return _distime; }
      set { _distime = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private uint _reset = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"reset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reset
    {
      get { return _reset; }
      set { _reset = value; }
    }
    private uint _partitype = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"partitype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint partitype
    {
      get { return _partitype; }
      set { _partitype = value; }
    }
    private uint _partivalue = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"partivalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint partivalue
    {
      get { return _partivalue; }
      set { _partivalue = value; }
    }
    private uint _pagetype = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pagetype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pagetype
    {
      get { return _pagetype; }
      set { _pagetype = value; }
    }
    private string _pagetitle = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"pagetitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pagetitle
    {
      get { return _pagetitle; }
      set { _pagetitle = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.GmActivityFinCond> _cond = new global::System.Collections.Generic.List<ProtoCmd.GmActivityFinCond>();
    [global::ProtoBuf.ProtoMember(14, Name=@"cond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.GmActivityFinCond> cond
    {
      get { return _cond; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmRewardData")]
  public partial class GmRewardData : global::ProtoBuf.IExtensible
  {
    public GmRewardData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _srvid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"srvid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> srvid
    {
      get { return _srvid; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.ActivityRewardData> _reward = new global::System.Collections.Generic.List<ProtoCmd.ActivityRewardData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ActivityRewardData> reward
    {
      get { return _reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmPVAIRankPlayer")]
  public partial class GmPVAIRankPlayer : global::ProtoBuf.IExtensible
  {
    public GmPVAIRankPlayer() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _career = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint career
    {
      get { return _career; }
      set { _career = value; }
    }
    private uint _lev = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lev
    {
      get { return _lev; }
      set { _lev = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private byte[] _recordtime = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"recordtime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] recordtime
    {
      get { return _recordtime; }
      set { _recordtime = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmFightRankPlayer")]
  public partial class GmFightRankPlayer : global::ProtoBuf.IExtensible
  {
    public GmFightRankPlayer() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _career = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint career
    {
      get { return _career; }
      set { _career = value; }
    }
    private uint _lev = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lev
    {
      get { return _lev; }
      set { _lev = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private byte[] _recordtime = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"recordtime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] recordtime
    {
      get { return _recordtime; }
      set { _recordtime = value; }
    }
    private uint _rank = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private byte[] _rolename = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rolename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] rolename
    {
      get { return _rolename; }
      set { _rolename = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedirectIpPort")]
  public partial class RedirectIpPort : global::ProtoBuf.IExtensible
  {
    public RedirectIpPort() {}
    
    private byte[] _ip = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GmNoticeStatus")]
    public enum GmNoticeStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmNoticeStatus_None", Value=0)]
      GmNoticeStatus_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmNoticeStatus_NotSend", Value=1)]
      GmNoticeStatus_NotSend = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmNoticeStatus_Sending", Value=2)]
      GmNoticeStatus_Sending = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmNoticeStatus_Finished", Value=3)]
      GmNoticeStatus_Finished = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmNoticeStatus_Max", Value=4)]
      GmNoticeStatus_Max = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GmFindPlayerType")]
    public enum GmFindPlayerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmFindPlayerType_Nam", Value=0)]
      GmFindPlayerType_Nam = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmFindPlayerType_Id", Value=1)]
      GmFindPlayerType_Id = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailErrorType")]
    public enum MailErrorType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailErrorType_WrongPlayer", Value=1)]
      MailErrorType_WrongPlayer = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailErrorType_TitleEmpty", Value=2)]
      MailErrorType_TitleEmpty = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailErrorType_ContentEmpty", Value=3)]
      MailErrorType_ContentEmpty = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailErrorType_TitleTooLong", Value=4)]
      MailErrorType_TitleTooLong = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailErrorType_ContentTooLong", Value=5)]
      MailErrorType_ContentTooLong = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GmReqRankType")]
    public enum GmReqRankType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmReqRankType_PVAI", Value=0)]
      GmReqRankType_PVAI = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmReqRankType_Fight", Value=1)]
      GmReqRankType_Fight = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GmDelItemRet")]
    public enum GmDelItemRet
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmDelItemRet_DelSucc", Value=0)]
      GmDelItemRet_DelSucc = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmDelItemRet_DelToDo", Value=1)]
      GmDelItemRet_DelToDo = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmDelItemRet_PlayerNotExist", Value=2)]
      GmDelItemRet_PlayerNotExist = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GmDelItemRet_ItemSubErr", Value=3)]
      GmDelItemRet_ItemSubErr = 3
    }
  
}