//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildAttr.proto
// Note: requires additional types generated from: LoginDefine.proto
// Note: requires additional types generated from: FbDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSetGuildAttrCmd")]
  public partial class ReqSetGuildAttrCmd : global::ProtoBuf.IExtensible
  {
    public ReqSetGuildAttrCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.AttrInfo> _attrs = new global::System.Collections.Generic.List<ProtoCmd.AttrInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.AttrInfo> attrs
    {
      get { return _attrs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetGuildAttrCmd")]
  public partial class ReqGetGuildAttrCmd : global::ProtoBuf.IExtensible
  {
    public ReqGetGuildAttrCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _keys = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"keys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> keys
    {
      get { return _keys; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspGetGuildAttrCmd")]
  public partial class RspGetGuildAttrCmd : global::ProtoBuf.IExtensible
  {
    public RspGetGuildAttrCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.AttrInfo> _attrs = new global::System.Collections.Generic.List<ProtoCmd.AttrInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.AttrInfo> attrs
    {
      get { return _attrs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildAttr")]
    public enum GuildAttr
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_BASE_START", Value=0)]
      ATTR_GUILD_BASE_START = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_ACTIVITY_NUM", Value=1)]
      ATTR_GUILD_ACTIVITY_NUM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_AUTO_ANSWER", Value=2)]
      ATTR_GUILD_AUTO_ANSWER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_WAR_SCORE", Value=101)]
      ATTR_GUILD_WAR_SCORE = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_WAR_RANK", Value=102)]
      ATTR_GUILD_WAR_RANK = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_WAR_FINALS_SCORE", Value=103)]
      ATTR_GUILD_WAR_FINALS_SCORE = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_WAR_FINALS_RANK", Value=104)]
      ATTR_GUILD_WAR_FINALS_RANK = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_RESOURCE_NUM", Value=201)]
      ATTR_GUILD_RESOURCE_NUM = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_OTHERWORLD_SCORE", Value=301)]
      ATTR_GUILD_OTHERWORLD_SCORE = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_OTHERWORLD_RANK", Value=302)]
      ATTR_GUILD_OTHERWORLD_RANK = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_BASE_END", Value=999)]
      ATTR_GUILD_BASE_END = 999,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CLIENT_START", Value=1000)]
      ATTR_GUILD_CLIENT_START = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CLIENT_AUTO_ANSWER", Value=1001)]
      ATTR_GUILD_CLIENT_AUTO_ANSWER = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CLIENT_END", Value=1100)]
      ATTR_GUILD_CLIENT_END = 1100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_START", Value=10000)]
      ATTR_GUILD_CONFIG_START = 10000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_IMPROVE", Value=10001)]
      ATTR_GUILD_CONFIG_DAILY_IMPROVE = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_SKILL", Value=10002)]
      ATTR_GUILD_CONFIG_DAILY_SKILL = 10002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_COMMON_FB", Value=10003)]
      ATTR_GUILD_CONFIG_DAILY_COMMON_FB = 10003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_BOSS_FB", Value=10004)]
      ATTR_GUILD_CONFIG_DAILY_BOSS_FB = 10004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_OUTSIDE", Value=10005)]
      ATTR_GUILD_CONFIG_DAILY_OUTSIDE = 10005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_LAYER", Value=10006)]
      ATTR_GUILD_CONFIG_DAILY_LAYER = 10006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_TREASURE", Value=10007)]
      ATTR_GUILD_CONFIG_DAILY_TREASURE = 10007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_PSYCHIC", Value=10008)]
      ATTR_GUILD_CONFIG_DAILY_PSYCHIC = 10008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_MILITARYRANK", Value=10009)]
      ATTR_GUILD_CONFIG_DAILY_MILITARYRANK = 10009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_PVE", Value=10010)]
      ATTR_GUILD_CONFIG_DAILY_PVE = 10010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_WBOSS", Value=10011)]
      ATTR_GUILD_CONFIG_DAILY_WBOSS = 10011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_PVAI", Value=10012)]
      ATTR_GUILD_CONFIG_DAILY_PVAI = 10012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_COIN", Value=10013)]
      ATTR_GUILD_CONFIG_DAILY_COIN = 10013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_SOUL", Value=10014)]
      ATTR_GUILD_CONFIG_DAILY_SOUL = 10014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_LOTTER", Value=10015)]
      ATTR_GUILD_CONFIG_DAILY_LOTTER = 10015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_TRAIN", Value=10016)]
      ATTR_GUILD_CONFIG_DAILY_TRAIN = 10016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_DAILY_LOGIN", Value=10100)]
      ATTR_GUILD_CONFIG_DAILY_LOGIN = 10100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_CONFIG_END", Value=11000)]
      ATTR_GUILD_CONFIG_END = 11000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_STRONGHOLD_START", Value=11001)]
      ATTR_GUILD_STRONGHOLD_START = 11001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTR_GUILD_STRONGHOLD_END", Value=12000)]
      ATTR_GUILD_STRONGHOLD_END = 12000
    }
  
}