//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildBaseData")]
  public partial class GuildBaseData : global::ProtoBuf.IExtensible
  {
    public GuildBaseData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _create_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"create_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint create_time
    {
      get { return _create_time; }
      set { _create_time = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _ranking = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private uint _member_num = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"member_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint member_num
    {
      get { return _member_num; }
      set { _member_num = value; }
    }
    private uint _member_limit = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"member_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint member_limit
    {
      get { return _member_limit; }
      set { _member_limit = value; }
    }
    private byte[] _leader_name = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"leader_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] leader_name
    {
      get { return _leader_name; }
      set { _leader_name = value; }
    }
    private byte[] _announce = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"announce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] announce
    {
      get { return _announce; }
      set { _announce = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberData")]
  public partial class MemberData : global::ProtoBuf.IExtensible
  {
    public MemberData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _role = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role
    {
      get { return _role; }
      set { _role = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private uint _last_offline_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"last_offline_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_offline_time
    {
      get { return _last_offline_time; }
      set { _last_offline_time = value; }
    }
    private uint _online = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint online
    {
      get { return _online; }
      set { _online = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildQueryData")]
  public partial class GuildQueryData : global::ProtoBuf.IExtensible
  {
    public GuildQueryData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _ranking = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private uint _member_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"member_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint member_num
    {
      get { return _member_num; }
      set { _member_num = value; }
    }
    private uint _member_limit = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"member_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint member_limit
    {
      get { return _member_limit; }
      set { _member_limit = value; }
    }
    private uint _leader_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"leader_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint leader_id
    {
      get { return _leader_id; }
      set { _leader_id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _leader_name = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"leader_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] leader_name
    {
      get { return _leader_name; }
      set { _leader_name = value; }
    }
    private bool _is_apply = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"is_apply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_apply
    {
      get { return _is_apply; }
      set { _is_apply = value; }
    }
    private uint _create_time = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"create_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint create_time
    {
      get { return _create_time; }
      set { _create_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildPlayerApplyData")]
  public partial class GuildPlayerApplyData : global::ProtoBuf.IExtensible
  {
    public GuildPlayerApplyData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _lev = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lev
    {
      get { return _lev; }
      set { _lev = value; }
    }
    private int _role = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int role
    {
      get { return _role; }
      set { _role = value; }
    }
    private uint _fight_strength = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fight_strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight_strength
    {
      get { return _fight_strength; }
      set { _fight_strength = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _last_offline_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"last_offline_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_offline_time
    {
      get { return _last_offline_time; }
      set { _last_offline_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildEventData")]
  public partial class GuildEventData : global::ProtoBuf.IExtensible
  {
    public GuildEventData() {}
    
    private uint _event = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"event", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint @event
    {
      get { return _event; }
      set { _event = value; }
    }
    private uint _time = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private byte[] _opetor = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"opetor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] opetor
    {
      get { return _opetor; }
      set { _opetor = value; }
    }
    private byte[] _acptor = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"acptor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] acptor
    {
      get { return _acptor; }
      set { _acptor = value; }
    }
    private int _data1 = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"data1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int data1
    {
      get { return _data1; }
      set { _data1 = value; }
    }
    private int _data2 = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"data2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int data2
    {
      get { return _data2; }
      set { _data2 = value; }
    }
    private int _data3 = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"data3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int data3
    {
      get { return _data3; }
      set { _data3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildBlessBaseData")]
  public partial class GuildBlessBaseData : global::ProtoBuf.IExtensible
  {
    public GuildBlessBaseData() {}
    
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _tcount = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tcount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tcount
    {
      get { return _tcount; }
      set { _tcount = value; }
    }
    private uint _cost = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cost
    {
      get { return _cost; }
      set { _cost = value; }
    }
    private uint _tcb = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tcb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tcb
    {
      get { return _tcb; }
      set { _tcb = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _val = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint val
    {
      get { return _val; }
      set { _val = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildLevelRankData")]
  public partial class GuildLevelRankData : global::ProtoBuf.IExtensible
  {
    public GuildLevelRankData() {}
    
    private uint _id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _num = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _max_num = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"max_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint max_num
    {
      get { return _max_num; }
      set { _max_num = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _leader_name = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"leader_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] leader_name
    {
      get { return _leader_name; }
      set { _leader_name = value; }
    }
    private uint _war_score = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"war_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint war_score
    {
      get { return _war_score; }
      set { _war_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildBlessRankData")]
  public partial class GuildBlessRankData : global::ProtoBuf.IExtensible
  {
    public GuildBlessRankData() {}
    
    private uint _bless = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bless", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bless
    {
      get { return _bless; }
      set { _bless = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureData")]
  public partial class TreasureData : global::ProtoBuf.IExtensible
  {
    public TreasureData() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IdentifyRecord")]
  public partial class IdentifyRecord : global::ProtoBuf.IExtensible
  {
    public IdentifyRecord() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _op_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private string _player_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private uint _guild_money = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"guild_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guild_money
    {
      get { return _guild_money; }
      set { _guild_money = value; }
    }
    private uint _contribution = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"contribution", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint contribution
    {
      get { return _contribution; }
      set { _contribution = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRankGuildData")]
  public partial class PlayerRankGuildData : global::ProtoBuf.IExtensible
  {
    public PlayerRankGuildData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private uint _score = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildWarMemberData")]
  public partial class GuildWarMemberData : global::ProtoBuf.IExtensible
  {
    public GuildWarMemberData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherWorldScoreRankData")]
  public partial class OtherWorldScoreRankData : global::ProtoBuf.IExtensible
  {
    public OtherWorldScoreRankData() {}
    
    private uint _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private byte[] _leader_name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"leader_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] leader_name
    {
      get { return _leader_name; }
      set { _leader_name = value; }
    }
    private uint _pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildMineData")]
  public partial class GuildMineData : global::ProtoBuf.IExtensible
  {
    public GuildMineData() {}
    
    private uint _mine_idx = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mine_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mine_idx
    {
      get { return _mine_idx; }
      set { _mine_idx = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private ulong _start_point = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong start_point
    {
      get { return _start_point; }
      set { _start_point = value; }
    }
    private uint _working_pet = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"working_pet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint working_pet
    {
      get { return _working_pet; }
      set { _working_pet = value; }
    }
    private uint _work_long = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"work_long", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint work_long
    {
      get { return _work_long; }
      set { _work_long = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildOtherDefine")]
    public enum GuildOtherDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_MAX_INTRODUCE_LEN", Value=200)]
      GUILD_MAX_INTRODUCE_LEN = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD_MAX_ANNOUNCE_LEN", Value=201)]
      GUILD_MAX_ANNOUNCE_LEN = 201
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildPostionType")]
    public enum GuildPostionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPostionType_Member", Value=0)]
      GuildPostionType_Member = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPostionType_Officer", Value=1)]
      GuildPostionType_Officer = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPostionType_ViceChairman", Value=2)]
      GuildPostionType_ViceChairman = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPostionType_Chairman", Value=3)]
      GuildPostionType_Chairman = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPostionType_Max", Value=4)]
      GuildPostionType_Max = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildPowerType")]
    public enum GuildPowerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_UpgradeGuild", Value=0)]
      GuildPowerType_UpgradeGuild = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_EditNotice", Value=1)]
      GuildPowerType_EditNotice = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_AppointVice", Value=2)]
      GuildPowerType_AppointVice = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_AppointOfficer", Value=3)]
      GuildPowerType_AppointOfficer = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_Kickout", Value=4)]
      GuildPowerType_Kickout = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_Recruit", Value=5)]
      GuildPowerType_Recruit = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_UpgradeSkill", Value=6)]
      GuildPowerType_UpgradeSkill = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildPowerType_ApplyFight", Value=7)]
      GuildPowerType_ApplyFight = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildOperType")]
    public enum GuildOperType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_UpgradeSkill", Value=0)]
      GuildOperType_UpgradeSkill = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_AddMember", Value=1)]
      GuildOperType_AddMember = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_KickMember", Value=2)]
      GuildOperType_KickMember = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_ChgAnnounce", Value=3)]
      GuildOperType_ChgAnnounce = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_Appoint", Value=4)]
      GuildOperType_Appoint = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_ApplyFight", Value=5)]
      GuildOperType_ApplyFight = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_ChgGuildName", Value=6)]
      GuildOperType_ChgGuildName = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_UpgradeGuild", Value=7)]
      GuildOperType_UpgradeGuild = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_LeaveStrongHold", Value=8)]
      GuildOperType_LeaveStrongHold = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_CreateGuild", Value=10)]
      GuildOperType_CreateGuild = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_ChangeLeader", Value=11)]
      GuildOperType_ChangeLeader = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_PlayerQuit", Value=12)]
      GuildOperType_PlayerQuit = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_PlayerApply", Value=13)]
      GuildOperType_PlayerApply = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_InvitePlayer", Value=14)]
      GuildOperType_InvitePlayer = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_AcceptInvite", Value=15)]
      GuildOperType_AcceptInvite = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_Contribution", Value=16)]
      GuildOperType_Contribution = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_BuyItem", Value=17)]
      GuildOperType_BuyItem = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_RequireEvent", Value=18)]
      GuildOperType_RequireEvent = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_UpgradePlayerSkill", Value=19)]
      GuildOperType_UpgradePlayerSkill = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_Bless", Value=20)]
      GuildOperType_Bless = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_PlayerCancelApply", Value=21)]
      GuildOperType_PlayerCancelApply = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildOperType_Max", Value=22)]
      GuildOperType_Max = 22
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildBuildingType")]
    public enum GuildBuildingType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBuildingType_Guild", Value=0)]
      GuildBuildingType_Guild = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBuildingType_SkillTower", Value=1)]
      GuildBuildingType_SkillTower = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBuildingType_Shop", Value=2)]
      GuildBuildingType_Shop = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBuildingType_Altar", Value=3)]
      GuildBuildingType_Altar = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBuildingType_Store", Value=4)]
      GuildBuildingType_Store = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBuildingType_End", Value=5)]
      GuildBuildingType_End = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildSkillType")]
    public enum GuildSkillType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_Strength", Value=1)]
      GuildSkillType_Strength = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_Armor", Value=2)]
      GuildSkillType_Armor = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_Intell", Value=3)]
      GuildSkillType_Intell = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_Captain", Value=4)]
      GuildSkillType_Captain = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_Physique", Value=5)]
      GuildSkillType_Physique = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_Gold", Value=6)]
      GuildSkillType_Gold = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildSkillType_End", Value=7)]
      GuildSkillType_End = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildBlessRewardType")]
    public enum GuildBlessRewardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_None", Value=0)]
      GuildBlessRewardType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Gold", Value=1)]
      GuildBlessRewardType_Gold = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_CashGift", Value=2)]
      GuildBlessRewardType_CashGift = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_FightSpirit", Value=3)]
      GuildBlessRewardType_FightSpirit = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Exp", Value=4)]
      GuildBlessRewardType_Exp = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Seed", Value=5)]
      GuildBlessRewardType_Seed = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_GainProps", Value=6)]
      GuildBlessRewardType_GainProps = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Medicine", Value=7)]
      GuildBlessRewardType_Medicine = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Chest", Value=8)]
      GuildBlessRewardType_Chest = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Gemstone", Value=9)]
      GuildBlessRewardType_Gemstone = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_ShopItems", Value=10)]
      GuildBlessRewardType_ShopItems = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildBlessRewardType_Max", Value=11)]
      GuildBlessRewardType_Max = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildEventType")]
    public enum GuildEventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_MemberAdd", Value=1)]
      GuildEventType_MemberAdd = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_MemberKite", Value=2)]
      GuildEventType_MemberKite = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_MemberPost", Value=3)]
      GuildEventType_MemberPost = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_Create", Value=4)]
      GuildEventType_Create = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_LeaderChangeName", Value=5)]
      GuildEventType_LeaderChangeName = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_BlessReward", Value=6)]
      GuildEventType_BlessReward = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_Transfer", Value=7)]
      GuildEventType_Transfer = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_DonateTreasure", Value=8)]
      GuildEventType_DonateTreasure = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_IdentifyTreasure", Value=9)]
      GuildEventType_IdentifyTreasure = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_NamePlayer", Value=100)]
      GuildEventType_NamePlayer = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_ResourceAttacked", Value=11)]
      GuildEventType_ResourceAttacked = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_War", Value=12)]
      GuildEventType_War = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildEventType_NameGuild", Value=200)]
      GuildEventType_NameGuild = 200
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResourceStatus")]
    public enum ResourceStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResourceStatus_Normal", Value=0)]
      ResourceStatus_Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResourceStatus_Protected", Value=1)]
      ResourceStatus_Protected = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResourceStatus_Attacked", Value=2)]
      ResourceStatus_Attacked = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResourceStatus_GiveUp", Value=3)]
      ResourceStatus_GiveUp = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"WarGroupState")]
    public enum WarGroupState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarGroupState_NULL", Value=0)]
      WarGroupState_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarGroupState_Match", Value=1)]
      WarGroupState_Match = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarGroupState_Ready", Value=2)]
      WarGroupState_Ready = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarGroupState_Fight", Value=3)]
      WarGroupState_Fight = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarGroupState_Sleep", Value=4)]
      WarGroupState_Sleep = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WarGroupState_Destory", Value=5)]
      WarGroupState_Destory = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildMineStatus")]
    public enum GuildMineStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildMineStatus_Undetect", Value=0)]
      GuildMineStatus_Undetect = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildMineStatus_Detected", Value=1)]
      GuildMineStatus_Detected = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuildMineStatus_Working", Value=2)]
      GuildMineStatus_Working = 2
    }
  
}