//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ItemDefine.proto
// Note: requires additional types generated from: SpiritStoneCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemLocation")]
  public partial class ItemLocation : global::ProtoBuf.IExtensible
  {
    public ItemLocation() {}
    
    private int _x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _z = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemBase")]
  public partial class ItemBase : global::ProtoBuf.IExtensible
  {
    public ItemBase() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private ulong _createid = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong createid
    {
      get { return _createid; }
      set { _createid = value; }
    }
    private ProtoCmd.ItemLocation _pos = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemAttrPair")]
  public partial class ItemAttrPair : global::ProtoBuf.IExtensible
  {
    public ItemAttrPair() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _val = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint val
    {
      get { return _val; }
      set { _val = value; }
    }
    private uint _rand_factor = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rand_factor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rand_factor
    {
      get { return _rand_factor; }
      set { _rand_factor = value; }
    }
    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemAttrData")]
  public partial class ItemAttrData : global::ProtoBuf.IExtensible
  {
    public ItemAttrData() {}
    
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemAttrPair> _attr_pair = new global::System.Collections.Generic.List<ProtoCmd.ItemAttrPair>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attr_pair", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemAttrPair> attr_pair
    {
      get { return _attr_pair; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemEquipAttrData")]
  public partial class ItemEquipAttrData : global::ProtoBuf.IExtensible
  {
    public ItemEquipAttrData() {}
    
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemAttrData> _attr_data = new global::System.Collections.Generic.List<ProtoCmd.ItemAttrData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attr_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemAttrData> attr_data
    {
      get { return _attr_data; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _equip_skill = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"equip_skill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> equip_skill
    {
      get { return _equip_skill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipRandAttrData")]
  public partial class EquipRandAttrData : global::ProtoBuf.IExtensible
  {
    public EquipRandAttrData() {}
    
    private int _attr = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _val = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipHoleData")]
  public partial class EquipHoleData : global::ProtoBuf.IExtensible
  {
    public EquipHoleData() {}
    
    private bool _enable = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable
    {
      get { return _enable; }
      set { _enable = value; }
    }
    private uint _item_base_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_base_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_base_id
    {
      get { return _item_base_id; }
      set { _item_base_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlessData")]
  public partial class BlessData : global::ProtoBuf.IExtensible
  {
    public BlessData() {}
    
    private uint _cur_value = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cur_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_value
    {
      get { return _cur_value; }
      set { _cur_value = value; }
    }
    private uint _max_value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_value
    {
      get { return _max_value; }
      set { _max_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemCommAttrData")]
  public partial class ItemCommAttrData : global::ProtoBuf.IExtensible
  {
    public ItemCommAttrData() {}
    
    private bool _isbind = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isbind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isbind
    {
      get { return _isbind; }
      set { _isbind = value; }
    }
    private uint _strength_lv = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"strength_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint strength_lv
    {
      get { return _strength_lv; }
      set { _strength_lv = value; }
    }
    private ProtoCmd.SpiritStoneData _spirit_stone_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"spirit_stone_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.SpiritStoneData spirit_stone_data
    {
      get { return _spirit_stone_data; }
      set { _spirit_stone_data = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.EquipHoleData> _hole_data = new global::System.Collections.Generic.List<ProtoCmd.EquipHoleData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"hole_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.EquipHoleData> hole_data
    {
      get { return _hole_data; }
    }
  
    private ProtoCmd.BlessData _bless_data = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bless_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.BlessData bless_data
    {
      get { return _bless_data; }
      set { _bless_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemSerialize")]
  public partial class ItemSerialize : global::ProtoBuf.IExtensible
  {
    public ItemSerialize() {}
    
    private ProtoCmd.ItemBase _base_data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemBase base_data
    {
      get { return _base_data; }
      set { _base_data = value; }
    }
    private ProtoCmd.ItemCommAttrData _comm_attr = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"comm_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemCommAttrData comm_attr
    {
      get { return _comm_attr; }
      set { _comm_attr = value; }
    }
    private ProtoCmd.ItemEquipAttrData _equip_attr = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equip_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemEquipAttrData equip_attr
    {
      get { return _equip_attr; }
      set { _equip_attr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipAttrStarData")]
  public partial class EquipAttrStarData : global::ProtoBuf.IExtensible
  {
    public EquipAttrStarData() {}
    
    private int _attr = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _val = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipStrengthenData")]
  public partial class EquipStrengthenData : global::ProtoBuf.IExtensible
  {
    public EquipStrengthenData() {}
    
    private uint _strength_lv = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strength_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint strength_lv
    {
      get { return _strength_lv; }
      set { _strength_lv = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemAttrPair> _attr_pair = new global::System.Collections.Generic.List<ProtoCmd.ItemAttrPair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attr_pair", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemAttrPair> attr_pair
    {
      get { return _attr_pair; }
    }
  
    private uint _order = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipGemstoneData")]
  public partial class EquipGemstoneData : global::ProtoBuf.IExtensible
  {
    public EquipGemstoneData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _enable = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable
    {
      get { return _enable; }
      set { _enable = value; }
    }
    private uint _gemstone_baseid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gemstone_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gemstone_baseid
    {
      get { return _gemstone_baseid; }
      set { _gemstone_baseid = value; }
    }
    private uint _attr_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"attr_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attr_type
    {
      get { return _attr_type; }
      set { _attr_type = value; }
    }
    private uint _attr_value = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"attr_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attr_value
    {
      get { return _attr_value; }
      set { _attr_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipPartData")]
  public partial class EquipPartData : global::ProtoBuf.IExtensible
  {
    public EquipPartData() {}
    
    private ProtoCmd.EquipStrengthenData _stengthen_data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stengthen_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.EquipStrengthenData stengthen_data
    {
      get { return _stengthen_data; }
      set { _stengthen_data = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.EquipGemstoneData> _gemstone_data = new global::System.Collections.Generic.List<ProtoCmd.EquipGemstoneData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"gemstone_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.EquipGemstoneData> gemstone_data
    {
      get { return _gemstone_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemGeneType")]
    public enum ItemGeneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_None", Value=0)]
      ItemGeneType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Consumable", Value=1)]
      ItemGeneType_Consumable = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Fashion", Value=2)]
      ItemGeneType_Fashion = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Chromosome", Value=3)]
      ItemGeneType_Chromosome = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Equip", Value=4)]
      ItemGeneType_Equip = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Material", Value=5)]
      ItemGeneType_Material = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Gemstone", Value=6)]
      ItemGeneType_Gemstone = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Quest", Value=7)]
      ItemGeneType_Quest = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Rune", Value=8)]
      ItemGeneType_Rune = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Contract", Value=9)]
      ItemGeneType_Contract = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Gold", Value=10)]
      ItemGeneType_Gold = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_ChangeName", Value=11)]
      ItemGeneType_ChangeName = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_SpiritStone", Value=12)]
      ItemGeneType_SpiritStone = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Card", Value=13)]
      ItemGeneType_Card = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_RawMaterial", Value=14)]
      ItemGeneType_RawMaterial = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemGeneType_Treasure", Value=15)]
      ItemGeneType_Treasure = 15
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemSubType_Equip")]
    public enum ItemSubType_Equip
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Begin", Value=0)]
      ItemSubType_Equip_Begin = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Weapon", Value=1)]
      ItemSubType_Equip_Weapon = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_ShoulderArmor", Value=2)]
      ItemSubType_Equip_ShoulderArmor = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Helmet", Value=3)]
      ItemSubType_Equip_Helmet = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_ChestArmor", Value=4)]
      ItemSubType_Equip_ChestArmor = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_ArmArmor", Value=5)]
      ItemSubType_Equip_ArmArmor = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Belt", Value=6)]
      ItemSubType_Equip_Belt = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Boots", Value=7)]
      ItemSubType_Equip_Boots = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Wing", Value=8)]
      ItemSubType_Equip_Wing = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Equip_Fashion", Value=9)]
      ItemSubType_Equip_Fashion = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipPostion")]
    public enum EquipPostion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_Weapon", Value=0)]
      EquipPosition_Weapon = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_ShoulderArmor", Value=1)]
      EquipPosition_ShoulderArmor = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_Helmet", Value=2)]
      EquipPosition_Helmet = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_ChestArmor", Value=3)]
      EquipPosition_ChestArmor = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_ArmArmor", Value=4)]
      EquipPosition_ArmArmor = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_Belt", Value=5)]
      EquipPosition_Belt = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_Boots", Value=6)]
      EquipPosition_Boots = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_Wing", Value=7)]
      EquipPosition_Wing = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipPosition_Fashion", Value=8)]
      EquipPosition_Fashion = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemSubType_Fashion")]
    public enum ItemSubType_Fashion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Fashion_Begin", Value=0)]
      ItemSubType_Fashion_Begin = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Fashion_Clothes", Value=1)]
      ItemSubType_Fashion_Clothes = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemSubType_Fashion_Wing", Value=2)]
      ItemSubType_Fashion_Wing = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FashionPostion")]
    public enum FashionPostion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionPosition_Clothes", Value=0)]
      FashionPosition_Clothes = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FashionPosition_Wing", Value=1)]
      FashionPosition_Wing = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemAttribute")]
    public enum ItemAttribute
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_None", Value=0)]
      ItemAttribute_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_BindMask", Value=1)]
      ItemAttribute_BindMask = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_UseTime", Value=2)]
      ItemAttribute_UseTime = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_OwnTime", Value=3)]
      ItemAttribute_OwnTime = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_DropTime", Value=4)]
      ItemAttribute_DropTime = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_DestroyTime", Value=5)]
      ItemAttribute_DestroyTime = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_HoleNum", Value=6)]
      ItemAttribute_HoleNum = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_Quality", Value=7)]
      ItemAttribute_Quality = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_StrengthLv", Value=8)]
      ItemAttribute_StrengthLv = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_HoleStone1", Value=9)]
      ItemAttribute_HoleStone1 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_HoleStone2", Value=10)]
      ItemAttribute_HoleStone2 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_HoleStone3", Value=11)]
      ItemAttribute_HoleStone3 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemAttribute_HoleStone4", Value=12)]
      ItemAttribute_HoleStone4 = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipAttrType")]
    public enum EquipAttrType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_None", Value=0)]
      EquipAttrType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Base_HP", Value=1)]
      EquipAttrType_Base_HP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Base_Attack", Value=2)]
      EquipAttrType_Base_Attack = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Base_Defend", Value=3)]
      EquipAttrType_Base_Defend = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Power", Value=4)]
      EquipAttrType_Power = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Intell", Value=5)]
      EquipAttrType_Intell = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Agile", Value=6)]
      EquipAttrType_Agile = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_HP", Value=8)]
      EquipAttrType_HP = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Att", Value=9)]
      EquipAttrType_Att = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Def", Value=10)]
      EquipAttrType_Def = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Power_per", Value=13)]
      EquipAttrType_Power_per = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Intell_per", Value=14)]
      EquipAttrType_Intell_per = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Agile_per", Value=15)]
      EquipAttrType_Agile_per = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_HP_per", Value=17)]
      EquipAttrType_HP_per = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Att_per", Value=18)]
      EquipAttrType_Att_per = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Def_per", Value=19)]
      EquipAttrType_Def_per = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Luck", Value=20)]
      EquipAttrType_Luck = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Luck_Rate", Value=21)]
      EquipAttrType_Luck_Rate = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Pierace", Value=22)]
      EquipAttrType_Pierace = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Pierace_Per", Value=23)]
      EquipAttrType_Pierace_Per = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Moon_Init", Value=24)]
      EquipAttrType_Moon_Init = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Moon_Factor", Value=25)]
      EquipAttrType_Moon_Factor = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Transform_Time", Value=26)]
      EquipAttrType_Transform_Time = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_CritLv", Value=38)]
      EquipAttrType_CritLv = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_DodgeLv", Value=39)]
      EquipAttrType_DodgeLv = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Steal_Health_Per", Value=40)]
      EquipAttrType_Steal_Health_Per = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Skill_Damage_Per_5", Value=41)]
      EquipAttrType_Skill_Damage_Per_5 = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Skill_Damage_Per_7", Value=42)]
      EquipAttrType_Skill_Damage_Per_7 = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Skill_Damage_Per_8", Value=43)]
      EquipAttrType_Skill_Damage_Per_8 = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Skill_Damage_Per_9", Value=44)]
      EquipAttrType_Skill_Damage_Per_9 = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Crit_Per", Value=45)]
      EquipAttrType_Crit_Per = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Dodge_Per", Value=46)]
      EquipAttrType_Dodge_Per = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_All_Second_Per", Value=47)]
      EquipAttrType_All_Second_Per = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrType_Max", Value=48)]
      EquipAttrType_Max = 48
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipSuitAttrType")]
    public enum EquipSuitAttrType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_None", Value=0)]
      EquipSuitAttrType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Power", Value=1)]
      EquipSuitAttrType_Power = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Intell", Value=2)]
      EquipSuitAttrType_Intell = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Agile", Value=3)]
      EquipSuitAttrType_Agile = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Body", Value=4)]
      EquipSuitAttrType_Body = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Phy_att", Value=5)]
      EquipSuitAttrType_Phy_att = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_MP_att", Value=6)]
      EquipSuitAttrType_MP_att = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Miss_Damage_per", Value=7)]
      EquipSuitAttrType_Miss_Damage_per = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Abnormal_per", Value=8)]
      EquipSuitAttrType_Abnormal_per = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Miss_Ice_Abnormal_per", Value=9)]
      EquipSuitAttrType_Miss_Ice_Abnormal_per = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Miss_Fire_Abnormal_per", Value=10)]
      EquipSuitAttrType_Miss_Fire_Abnormal_per = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Miss_Ele_Abnormal_per", Value=11)]
      EquipSuitAttrType_Miss_Ele_Abnormal_per = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Miss_Poison_Abnormal_per", Value=12)]
      EquipSuitAttrType_Miss_Poison_Abnormal_per = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipSuitAttrType_Max", Value=13)]
      EquipSuitAttrType_Max = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipAttrGeneType")]
    public enum EquipAttrGeneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrGeneType_Base", Value=0)]
      EquipAttrGeneType_Base = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrGeneType_Additional", Value=1)]
      EquipAttrGeneType_Additional = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrGeneType_SpiritStone", Value=2)]
      EquipAttrGeneType_SpiritStone = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrGeneType_Hole1", Value=3)]
      EquipAttrGeneType_Hole1 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrGeneType_Hole2", Value=4)]
      EquipAttrGeneType_Hole2 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipAttrGeneType_Hole3", Value=5)]
      EquipAttrGeneType_Hole3 = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PackageSubType")]
    public enum PackageSubType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_None", Value=0)]
      PackageSubType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_Equip", Value=1)]
      PackageSubType_Equip = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_Fashion", Value=2)]
      PackageSubType_Fashion = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_Common", Value=3)]
      PackageSubType_Common = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_EquipCommon", Value=5)]
      PackageSubType_EquipCommon = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_Stone", Value=6)]
      PackageSubType_Stone = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_Weapon", Value=7)]
      PackageSubType_Weapon = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackageSubType_Treasure", Value=8)]
      PackageSubType_Treasure = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemOperationType")]
    public enum ItemOperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_None", Value=0)]
      ItemOperationType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Remove", Value=1)]
      ItemOperationType_Remove = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Move", Value=2)]
      ItemOperationType_Move = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Swap", Value=3)]
      ItemOperationType_Swap = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Split", Value=4)]
      ItemOperationType_Split = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Union", Value=5)]
      ItemOperationType_Union = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Use", Value=6)]
      ItemOperationType_Use = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Sell", Value=7)]
      ItemOperationType_Sell = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_BatchSell", Value=8)]
      ItemOperationType_BatchSell = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemOperationType_Use2Npc", Value=9)]
      ItemOperationType_Use2Npc = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipImproveOpType")]
    public enum EquipImproveOpType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_None", Value=0)]
      EquipImproveOpType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Reform", Value=1)]
      EquipImproveOpType_Reform = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Strengthen", Value=2)]
      EquipImproveOpType_Strengthen = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_TakeOutStone", Value=3)]
      EquipImproveOpType_TakeOutStone = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_EmbedStone", Value=4)]
      EquipImproveOpType_EmbedStone = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Merge", Value=5)]
      EquipImproveOpType_Merge = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Advance", Value=6)]
      EquipImproveOpType_Advance = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_EmbedRune", Value=7)]
      EquipImproveOpType_EmbedRune = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_TakeOutRune", Value=8)]
      EquipImproveOpType_TakeOutRune = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_RuneAdvance", Value=9)]
      EquipImproveOpType_RuneAdvance = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Decompose", Value=10)]
      EquipImproveOpType_Decompose = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Fuse", Value=11)]
      EquipImproveOpType_Fuse = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_WingAdvance", Value=12)]
      EquipImproveOpType_WingAdvance = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_StrengthenWeapon", Value=13)]
      EquipImproveOpType_StrengthenWeapon = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_ReformSpiritStone", Value=14)]
      EquipImproveOpType_ReformSpiritStone = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_RevertSpiritStone", Value=15)]
      EquipImproveOpType_RevertSpiritStone = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_EmbedSpiritStone", Value=16)]
      EquipImproveOpType_EmbedSpiritStone = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_TakeOutSpiritStone", Value=17)]
      EquipImproveOpType_TakeOutSpiritStone = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_SpiritStoneUpgrade", Value=18)]
      EquipImproveOpType_SpiritStoneUpgrade = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_ReformConfirm", Value=19)]
      EquipImproveOpType_ReformConfirm = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveOpType_Transfer", Value=20)]
      EquipImproveOpType_Transfer = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AddItemAction")]
    public enum AddItemAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_None", Value=0)]
      AddItemAction_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_LoadCommonPack", Value=1)]
      AddItemAction_LoadCommonPack = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_LoadStorage", Value=2)]
      AddItemAction_LoadStorage = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Move", Value=3)]
      AddItemAction_Move = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Split", Value=4)]
      AddItemAction_Split = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Union", Value=5)]
      AddItemAction_Union = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Quest", Value=6)]
      AddItemAction_Quest = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Script", Value=7)]
      AddItemAction_Script = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GMAdd", Value=8)]
      AddItemAction_GMAdd = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Shop", Value=9)]
      AddItemAction_Shop = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Booth", Value=10)]
      AddItemAction_Booth = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Trade", Value=11)]
      AddItemAction_Trade = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_PlayerPick", Value=12)]
      AddItemAction_PlayerPick = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Subaltern", Value=13)]
      AddItemAction_Subaltern = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_SubalternPick", Value=14)]
      AddItemAction_SubalternPick = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_TakeoutEquipStone", Value=15)]
      AddItemAction_TakeoutEquipStone = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_TakeoutEquipStar", Value=16)]
      AddItemAction_TakeoutEquipStar = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_ItemMerge", Value=17)]
      AddItemAction_ItemMerge = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_EquipDecompose", Value=18)]
      AddItemAction_EquipDecompose = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_StoneConvert", Value=19)]
      AddItemAction_StoneConvert = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_PickFromMail", Value=20)]
      AddItemAction_PickFromMail = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_EquipReform", Value=21)]
      AddItemAction_EquipReform = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_EquipStrengthen", Value=22)]
      AddItemAction_EquipStrengthen = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_EquipMakeHole", Value=23)]
      AddItemAction_EquipMakeHole = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_EquipEmbed", Value=24)]
      AddItemAction_EquipEmbed = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_ExchangeItem", Value=25)]
      AddItemAction_ExchangeItem = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_BuyFromGuildShop", Value=26)]
      AddItemAction_BuyFromGuildShop = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Bless", Value=27)]
      AddItemAction_Bless = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_BattleAward", Value=28)]
      AddItemAction_BattleAward = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDItemAction_MonsterLost", Value=29)]
      ADDItemAction_MonsterLost = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Mall", Value=30)]
      AddItemAction_Mall = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Gift", Value=31)]
      AddItemAction_Gift = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_InitNewPlayer", Value=32)]
      AddItemAction_InitNewPlayer = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Fuse", Value=33)]
      AddItemAction_Fuse = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Compass", Value=34)]
      AddItemAction_Compass = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_TreasureChest", Value=35)]
      AddItemAction_TreasureChest = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Power", Value=36)]
      AddItemAction_Power = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_RunePray", Value=37)]
      AddItemAction_RunePray = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GeneResearchRob", Value=38)]
      AddItemAction_GeneResearchRob = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GeneResearchAward", Value=39)]
      AddItemAction_GeneResearchAward = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Business", Value=40)]
      AddItemAction_Business = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Activity", Value=41)]
      AddItemAction_Activity = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_VIP", Value=42)]
      AddItemAction_VIP = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Login", Value=43)]
      AddItemAction_Login = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_WBOSS_REWARD", Value=44)]
      AddItemAction_WBOSS_REWARD = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_PVAI_REWARD", Value=45)]
      AddItemAction_PVAI_REWARD = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GBOSS_REWARD_GUILD", Value=46)]
      AddItemAction_GBOSS_REWARD_GUILD = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GBOSS_REWARD_PLAYER", Value=47)]
      AddItemAction_GBOSS_REWARD_PLAYER = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GWAR_REWARD_GUILD", Value=48)]
      AddItemAction_GWAR_REWARD_GUILD = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GWAR_REWARD_PLAYER", Value=49)]
      AddItemAction_GWAR_REWARD_PLAYER = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_GWAR_REWARD_POINT", Value=50)]
      AddItemAction_GWAR_REWARD_POINT = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_SacrificeRank", Value=51)]
      AddItemAction_SacrificeRank = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Gift_VIP_Double", Value=52)]
      AddItemAction_Gift_VIP_Double = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemAction_Max", Value=53)]
      AddItemAction_Max = 53
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DelItemAction")]
    public enum DelItemAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_None", Value=200)]
      DelItemAction_None = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_PlayerDrop", Value=201)]
      DelItemAction_PlayerDrop = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Unreg", Value=202)]
      DelItemAction_Unreg = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_ChgMap", Value=203)]
      DelItemAction_ChgMap = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_TimeUpDrop", Value=204)]
      DelItemAction_TimeUpDrop = 204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_TimeUpDestroy", Value=205)]
      DelItemAction_TimeUpDestroy = 205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_DieDestroy", Value=206)]
      DelItemAction_DieDestroy = 206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_DieDrop", Value=207)]
      DelItemAction_DieDrop = 207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Uinon", Value=208)]
      DelItemAction_Uinon = 208,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_UseItem", Value=209)]
      DelItemAction_UseItem = 209,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_UseAmmu", Value=210)]
      DelItemAction_UseAmmu = 210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_LearnSkill", Value=211)]
      DelItemAction_LearnSkill = 211,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_WorldSay", Value=212)]
      DelItemAction_WorldSay = 212,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_LuaScript", Value=213)]
      DelItemAction_LuaScript = 213,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipImprove", Value=214)]
      DelItemAction_EquipImprove = 214,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Sell", Value=215)]
      DelItemAction_Sell = 215,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Shop", Value=216)]
      DelItemAction_Shop = 216,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_GmCmd", Value=217)]
      DelItemAction_GmCmd = 217,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_BoothSell", Value=218)]
      DelItemAction_BoothSell = 218,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_RecruitSubaltern", Value=219)]
      DelItemAction_RecruitSubaltern = 219,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Subaltern", Value=220)]
      DelItemAction_Subaltern = 220,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Split", Value=221)]
      DelItemAction_Split = 221,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Quest", Value=222)]
      DelItemAction_Quest = 222,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Script", Value=223)]
      DelItemAction_Script = 223,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_MergeOldEquip", Value=224)]
      DelItemAction_MergeOldEquip = 224,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Move", Value=225)]
      DelItemAction_Move = 225,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Mail", Value=226)]
      DelItemAction_Mail = 226,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_ArmyResFight", Value=227)]
      DelItemAction_ArmyResFight = 227,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipDecompose", Value=228)]
      DelItemAction_EquipDecompose = 228,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_StoneConvert", Value=229)]
      DelItemAction_StoneConvert = 229,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_ItemMerge", Value=230)]
      DelItemAction_ItemMerge = 230,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipReform", Value=231)]
      DelItemAction_EquipReform = 231,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipStrengthen", Value=232)]
      DelItemAction_EquipStrengthen = 232,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipMakeStone", Value=233)]
      DelItemAction_EquipMakeStone = 233,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipEmbed", Value=234)]
      DelItemAction_EquipEmbed = 234,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_ExchangeItem", Value=235)]
      DelItemAction_ExchangeItem = 235,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_QuitGuild", Value=236)]
      DelItemAction_QuitGuild = 236,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_WerwolfImprove", Value=237)]
      DelItemAction_WerwolfImprove = 237,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_AuctionGoods", Value=238)]
      DelItemAction_AuctionGoods = 238,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_FeedSprite", Value=239)]
      DelItemAction_FeedSprite = 239,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipAdvance", Value=240)]
      DelItemAction_EquipAdvance = 240,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_PresentGift", Value=241)]
      DelItemAction_PresentGift = 241,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipStoneAdvance", Value=242)]
      DelItemAction_EquipStoneAdvance = 242,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_RuneTransfer", Value=243)]
      DelItemAction_RuneTransfer = 243,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Wipe", Value=244)]
      DelItemAction_Wipe = 244,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_ChangeName", Value=245)]
      DelItemAction_ChangeName = 245,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_EquipTransfer", Value=246)]
      DelItemAction_EquipTransfer = 246,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelItemAction_Max", Value=247)]
      DelItemAction_Max = 247
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"WingCostType")]
    public enum WingCostType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WingCostType_Metarial", Value=1)]
      WingCostType_Metarial = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WingCostType_Diamond", Value=2)]
      WingCostType_Diamond = 2
    }
  
}