//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ItemCommand.proto
// Note: requires additional types generated from: ItemDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddItemListItemClientCmd")]
  public partial class AddItemListItemClientCmd : global::ProtoBuf.IExtensible
  {
    public AddItemListItemClientCmd() {}
    
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _item_num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> _data = new global::System.Collections.Generic.List<ProtoCmd.ItemSerialize>();
    [global::ProtoBuf.ProtoMember(3, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddDataItemClientCmd")]
  public partial class AddDataItemClientCmd : global::ProtoBuf.IExtensible
  {
    public AddDataItemClientCmd() {}
    
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private ProtoCmd.ItemSerialize _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemSerialize data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveDataItemClientCmd")]
  public partial class RemoveDataItemClientCmd : global::ProtoBuf.IExtensible
  {
    public RemoveDataItemClientCmd() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _pack = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pack
    {
      get { return _pack; }
      set { _pack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapItemClientCmd")]
  public partial class SwapItemClientCmd : global::ProtoBuf.IExtensible
  {
    public SwapItemClientCmd() {}
    
    private uint _src_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"src_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_thisid
    {
      get { return _src_thisid; }
      set { _src_thisid = value; }
    }
    private uint _dest_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dest_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_thisid
    {
      get { return _dest_thisid; }
      set { _dest_thisid = value; }
    }
    private ProtoCmd.ItemLocation _src_pos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"src_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation src_pos
    {
      get { return _src_pos; }
      set { _src_pos = value; }
    }
    private ProtoCmd.ItemLocation _dest_pos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dest_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation dest_pos
    {
      get { return _dest_pos; }
      set { _dest_pos = value; }
    }
    private ProtoCmd.ItemLocation _src_swap_pos = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"src_swap_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation src_swap_pos
    {
      get { return _src_swap_pos; }
      set { _src_swap_pos = value; }
    }
    private ProtoCmd.ItemLocation _dest_swap_pos = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dest_swap_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation dest_swap_pos
    {
      get { return _dest_swap_pos; }
      set { _dest_swap_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SplitItemClientCmd")]
  public partial class SplitItemClientCmd : global::ProtoBuf.IExtensible
  {
    public SplitItemClientCmd() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _dest_x = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dest_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dest_x
    {
      get { return _dest_x; }
      set { _dest_x = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnionItemClientCmd")]
  public partial class UnionItemClientCmd : global::ProtoBuf.IExtensible
  {
    public UnionItemClientCmd() {}
    
    private uint _src_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"src_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_thisid
    {
      get { return _src_thisid; }
      set { _src_thisid = value; }
    }
    private uint _dst_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dst_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dst_thisid
    {
      get { return _dst_thisid; }
      set { _dst_thisid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshCountItemClientCmd")]
  public partial class RefreshCountItemClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshCountItemClientCmd() {}
    
    private bool _is_add = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_add", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_add
    {
      get { return _is_add; }
      set { _is_add = value; }
    }
    private uint _action = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action
    {
      get { return _action; }
      set { _action = value; }
    }
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _pack = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pack
    {
      get { return _pack; }
      set { _pack = value; }
    }
    private uint _use_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"use_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint use_time
    {
      get { return _use_time; }
      set { _use_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshLocationItemClientCmd")]
  public partial class RefreshLocationItemClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshLocationItemClientCmd() {}
    
    private uint _action = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action
    {
      get { return _action; }
      set { _action = value; }
    }
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private ProtoCmd.ItemLocation _loc = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation loc
    {
      get { return _loc; }
      set { _loc = value; }
    }
    private ProtoCmd.ItemLocation _oldloc = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"oldloc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation oldloc
    {
      get { return _oldloc; }
      set { _oldloc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseItemClientCmd")]
  public partial class UseItemClientCmd : global::ProtoBuf.IExtensible
  {
    public UseItemClientCmd() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveItemClientCmd")]
  public partial class MoveItemClientCmd : global::ProtoBuf.IExtensible
  {
    public MoveItemClientCmd() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private ProtoCmd.ItemLocation _dst = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemLocation dst
    {
      get { return _dst; }
      set { _dst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseItemOperationItemClientCmd")]
  public partial class ResponseItemOperationItemClientCmd : global::ProtoBuf.IExtensible
  {
    public ResponseItemOperationItemClientCmd() {}
    
    private int _ret = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private int _op_type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseItemToNpcClientCmd")]
  public partial class UseItemToNpcClientCmd : global::ProtoBuf.IExtensible
  {
    public UseItemToNpcClientCmd() {}
    
    private uint _this_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"this_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint this_id
    {
      get { return _this_id; }
      set { _this_id = value; }
    }
    private uint _npc_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SellItemClientCmd")]
  public partial class SellItemClientCmd : global::ProtoBuf.IExtensible
  {
    public SellItemClientCmd() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatchSellItemClientCmd")]
  public partial class BatchSellItemClientCmd : global::ProtoBuf.IExtensible
  {
    public BatchSellItemClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _thisid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> thisid
    {
      get { return _thisid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildStorOperItemClientCmd")]
  public partial class GuildStorOperItemClientCmd : global::ProtoBuf.IExtensible
  {
    public GuildStorOperItemClientCmd() {}
    
    private ProtoCmd.GuildStorOperItemClientCmd.Type _type = ProtoCmd.GuildStorOperItemClientCmd.Type.Close;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.GuildStorOperItemClientCmd.Type.Close)]
    public ProtoCmd.GuildStorOperItemClientCmd.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Close", Value=0)]
      Close = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Open", Value=1)]
      Open = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FreshGuildStorItemClientCmd")]
  public partial class FreshGuildStorItemClientCmd : global::ProtoBuf.IExtensible
  {
    public FreshGuildStorItemClientCmd() {}
    
    private uint _cap = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cap
    {
      get { return _cap; }
      set { _cap = value; }
    }
    private bool _append = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"append", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool append
    {
      get { return _append; }
      set { _append = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> _data = new global::System.Collections.Generic.List<ProtoCmd.ItemSerialize>();
    [global::ProtoBuf.ProtoMember(3, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipSuitAttr")]
  public partial class EquipSuitAttr : global::ProtoBuf.IExtensible
  {
    public EquipSuitAttr() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshEquipSuitAttrClientCmd")]
  public partial class RefreshEquipSuitAttrClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshEquipSuitAttrClientCmd() {}
    
    private uint _suit_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"suit_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint suit_id
    {
      get { return _suit_id; }
      set { _suit_id = value; }
    }
    private readonly global::System.Collections.Generic.List<bool> _equip_pos = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equip_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> equip_pos
    {
      get { return _equip_pos; }
    }
  
    private uint _collect_num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"collect_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint collect_num
    {
      get { return _collect_num; }
      set { _collect_num = value; }
    }
    private uint _link_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"link_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_num
    {
      get { return _link_num; }
      set { _link_num = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.EquipSuitAttr> _suit_attr = new global::System.Collections.Generic.List<ProtoCmd.EquipSuitAttr>();
    [global::ProtoBuf.ProtoMember(5, Name=@"suit_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.EquipSuitAttr> suit_attr
    {
      get { return _suit_attr; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveResponseClientCmd")]
  public partial class EquipImproveResponseClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveResponseClientCmd() {}
    
    private int _optype = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"optype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int optype
    {
      get { return _optype; }
      set { _optype = value; }
    }
    private uint _ret = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveReformClientCmd")]
  public partial class EquipImproveReformClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveReformClientCmd() {}
    
    private uint _equip_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_id
    {
      get { return _equip_id; }
      set { _equip_id = value; }
    }
    private uint _attr_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attr_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attr_id
    {
      get { return _attr_id; }
      set { _attr_id = value; }
    }
    private uint _cost_equip_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cost_equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cost_equip_id
    {
      get { return _cost_equip_id; }
      set { _cost_equip_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveReformConfirmClientCmd")]
  public partial class EquipImproveReformConfirmClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveReformConfirmClientCmd() {}
    
    private uint _equip_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_id
    {
      get { return _equip_id; }
      set { _equip_id = value; }
    }
    private bool _is_confirm = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_confirm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_confirm
    {
      get { return _is_confirm; }
      set { _is_confirm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveReformResultClientCmd")]
  public partial class EquipImproveReformResultClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveReformResultClientCmd() {}
    
    private ProtoCmd.ItemAttrPair _old_attr = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"old_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemAttrPair old_attr
    {
      get { return _old_attr; }
      set { _old_attr = value; }
    }
    private ProtoCmd.ItemAttrPair _new_attr = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"new_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ItemAttrPair new_attr
    {
      get { return _new_attr; }
      set { _new_attr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveReformTransferClientCmd")]
  public partial class EquipImproveReformTransferClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveReformTransferClientCmd() {}
    
    private uint _equip_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_id
    {
      get { return _equip_id; }
      set { _equip_id = value; }
    }
    private uint _cost_equip_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cost_equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cost_equip_id
    {
      get { return _cost_equip_id; }
      set { _cost_equip_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveReformClearClientCmd")]
  public partial class EquipImproveReformClearClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveReformClearClientCmd() {}
    
    private uint _thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveStrengthenClientCmd")]
  public partial class EquipImproveStrengthenClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveStrengthenClientCmd() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private bool _is_auto = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_auto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_auto
    {
      get { return _is_auto; }
      set { _is_auto = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrengthenWeaponClientCmd")]
  public partial class StrengthenWeaponClientCmd : global::ProtoBuf.IExtensible
  {
    public StrengthenWeaponClientCmd() {}
    
    private uint _weapon_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"weapon_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weapon_thisid
    {
      get { return _weapon_thisid; }
      set { _weapon_thisid = value; }
    }
    private bool _is_use_prop = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_use_prop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_use_prop
    {
      get { return _is_use_prop; }
      set { _is_use_prop = value; }
    }
    private bool _is_advance = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_advance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_advance
    {
      get { return _is_advance; }
      set { _is_advance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WingAdvanceClientCmd")]
  public partial class WingAdvanceClientCmd : global::ProtoBuf.IExtensible
  {
    public WingAdvanceClientCmd() {}
    
    private uint _equip_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equip_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_thisid
    {
      get { return _equip_thisid; }
      set { _equip_thisid = value; }
    }
    private bool _is_auto = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_auto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_auto
    {
      get { return _is_auto; }
      set { _is_auto = value; }
    }
    private uint _type = (uint)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWingUnLockCmd")]
  public partial class ReqWingUnLockCmd : global::ProtoBuf.IExtensible
  {
    public ReqWingUnLockCmd() {}
    
    private uint _equip_thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equip_thisid
    {
      get { return _equip_thisid; }
      set { _equip_thisid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspWingUnLockCmd")]
  public partial class RspWingUnLockCmd : global::ProtoBuf.IExtensible
  {
    public RspWingUnLockCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipAdvanceClientCmd")]
  public partial class EquipAdvanceClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipAdvanceClientCmd() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private bool _is_advance = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_advance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_advance
    {
      get { return _is_advance; }
      set { _is_advance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveInlayClientCmd")]
  public partial class EquipImproveInlayClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveInlayClientCmd() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _stone_baseid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stone_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stone_baseid
    {
      get { return _stone_baseid; }
      set { _stone_baseid = value; }
    }
    private uint _hole_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hole_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hole_id
    {
      get { return _hole_id; }
      set { _hole_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveTakeOutStoneClientCmd")]
  public partial class EquipImproveTakeOutStoneClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveTakeOutStoneClientCmd() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _hole_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hole_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hole_id
    {
      get { return _hole_id; }
      set { _hole_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveDecomposeClientCmd")]
  public partial class EquipImproveDecomposeClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveDecomposeClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _equip_thisid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equip_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> equip_thisid
    {
      get { return _equip_thisid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RateItemData")]
  public partial class RateItemData : global::ProtoBuf.IExtensible
  {
    public RateItemData() {}
    
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResultEquipDecomposeClientCmd")]
  public partial class ResultEquipDecomposeClientCmd : global::ProtoBuf.IExtensible
  {
    public ResultEquipDecomposeClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.RateItemData> _item = new global::System.Collections.Generic.List<ProtoCmd.RateItemData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.RateItemData> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveStoneConvertClientCmd")]
  public partial class EquipImproveStoneConvertClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveStoneConvertClientCmd() {}
    
    private uint _src_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"src_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_thisid
    {
      get { return _src_thisid; }
      set { _src_thisid = value; }
    }
    private uint _dst_baseid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dst_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dst_baseid
    {
      get { return _dst_baseid; }
      set { _dst_baseid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveMergeClientCmd")]
  public partial class EquipImproveMergeClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveMergeClientCmd() {}
    
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private uint _num = (uint)1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private bool _is_auto = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_auto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_auto
    {
      get { return _is_auto; }
      set { _is_auto = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveStoneAdvanceClientCmd")]
  public partial class EquipImproveStoneAdvanceClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveStoneAdvanceClientCmd() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _hole_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hole_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hole_id
    {
      get { return _hole_id; }
      set { _hole_id = value; }
    }
    private bool _is_advance = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_advance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_advance
    {
      get { return _is_advance; }
      set { _is_advance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipImproveFuseClientCmd")]
  public partial class EquipImproveFuseClientCmd : global::ProtoBuf.IExtensible
  {
    public EquipImproveFuseClientCmd() {}
    
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllLearnedComposeFormulaClientCmd")]
  public partial class AllLearnedComposeFormulaClientCmd : global::ProtoBuf.IExtensible
  {
    public AllLearnedComposeFormulaClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> id
    {
      get { return _id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LearnedComposeFormulaClientCmd")]
  public partial class LearnedComposeFormulaClientCmd : global::ProtoBuf.IExtensible
  {
    public LearnedComposeFormulaClientCmd() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _ret = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshEquipPartListClientCmd")]
  public partial class RefreshEquipPartListClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshEquipPartListClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.EquipPartData> _part_data = new global::System.Collections.Generic.List<ProtoCmd.EquipPartData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"part_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.EquipPartData> part_data
    {
      get { return _part_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateEquipPartClientCmd")]
  public partial class UpdateEquipPartClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateEquipPartClientCmd() {}
    
    private uint _pos = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ProtoCmd.EquipPartData _part_data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"part_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.EquipPartData part_data
    {
      get { return _part_data; }
      set { _part_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWingSwapClientCmd")]
  public partial class ReqWingSwapClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqWingSwapClientCmd() {}
    
    private uint _equip_thisid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equip_thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_thisid
    {
      get { return _equip_thisid; }
      set { _equip_thisid = value; }
    }
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}