//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LotteryCommand.proto
// Note: requires additional types generated from: ErrorCode.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LotteryItem")]
  public partial class LotteryItem : global::ProtoBuf.IExtensible
  {
    public LotteryItem() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompassItem")]
  public partial class CompassItem : global::ProtoBuf.IExtensible
  {
    public CompassItem() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private uint _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRefreshCompassClientCmd")]
  public partial class ReqRefreshCompassClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqRefreshCompassClientCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspRefreshCompassClientCmd")]
  public partial class RspRefreshCompassClientCmd : global::ProtoBuf.IExtensible
  {
    public RspRefreshCompassClientCmd() {}
    
    private ProtoCmd.ErrorCode _ret = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_id
    {
      get { return _item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_num
    {
      get { return _item_num; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCompassLotteryClientCmd")]
  public partial class ReqCompassLotteryClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqCompassLotteryClientCmd() {}
    
    private uint _is_full = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_full", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_full
    {
      get { return _is_full; }
      set { _is_full = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspCompassLotteryClientCmd")]
  public partial class RspCompassLotteryClientCmd : global::ProtoBuf.IExtensible
  {
    public RspCompassLotteryClientCmd() {}
    
    private ProtoCmd.ErrorCode _ret = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.CompassItem> _item = new global::System.Collections.Generic.List<ProtoCmd.CompassItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.CompassItem> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendCompassItemsClientCmd")]
  public partial class SendCompassItemsClientCmd : global::ProtoBuf.IExtensible
  {
    public SendCompassItemsClientCmd() {}
    
    private ulong _next_auto_refresh_time = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"next_auto_refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong next_auto_refresh_time
    {
      get { return _next_auto_refresh_time; }
      set { _next_auto_refresh_time = value; }
    }
    private uint _refresh_cost = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"refresh_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint refresh_cost
    {
      get { return _refresh_cost; }
      set { _refresh_cost = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _full_draw_cost = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"full_draw_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> full_draw_cost
    {
      get { return _full_draw_cost; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_id
    {
      get { return _item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _item_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_num
    {
      get { return _item_num; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _draw_cost = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"draw_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> draw_cost
    {
      get { return _draw_cost; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqTreasureChestLotteryClientCmd")]
  public partial class ReqTreasureChestLotteryClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqTreasureChestLotteryClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private bool _is_ten = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_ten", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_ten
    {
      get { return _is_ten; }
      set { _is_ten = value; }
    }
    private bool _is_free = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_free", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_free
    {
      get { return _is_free; }
      set { _is_free = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspTreasureChestLotteryClientCmd")]
  public partial class RspTreasureChestLotteryClientCmd : global::ProtoBuf.IExtensible
  {
    public RspTreasureChestLotteryClientCmd() {}
    
    private ProtoCmd.ErrorCode _ret = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.LotteryItem> _item = new global::System.Collections.Generic.List<ProtoCmd.LotteryItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.LotteryItem> item
    {
      get { return _item; }
    }
  
    private bool _is_free = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_free", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_free
    {
      get { return _is_free; }
      set { _is_free = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TreasureChestInfo")]
  public partial class TreasureChestInfo : global::ProtoBuf.IExtensible
  {
    public TreasureChestInfo() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _max_free_draw_cnt = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_free_draw_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_free_draw_cnt
    {
      get { return _max_free_draw_cnt; }
      set { _max_free_draw_cnt = value; }
    }
    private uint _free_drawn_cnt = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"free_drawn_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint free_drawn_cnt
    {
      get { return _free_drawn_cnt; }
      set { _free_drawn_cnt = value; }
    }
    private uint _free_draw_interval = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"free_draw_interval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint free_draw_interval
    {
      get { return _free_draw_interval; }
      set { _free_draw_interval = value; }
    }
    private uint _left_cd_time = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"left_cd_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint left_cd_time
    {
      get { return _left_cd_time; }
      set { _left_cd_time = value; }
    }
    private uint _draw_cost = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"draw_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint draw_cost
    {
      get { return _draw_cost; }
      set { _draw_cost = value; }
    }
    private uint _ten_draw_cost = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ten_draw_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ten_draw_cost
    {
      get { return _ten_draw_cost; }
      set { _ten_draw_cost = value; }
    }
    private uint _draw_cost_type = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"draw_cost_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint draw_cost_type
    {
      get { return _draw_cost_type; }
      set { _draw_cost_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendTreasureChestInfoClientCmd")]
  public partial class SendTreasureChestInfoClientCmd : global::ProtoBuf.IExtensible
  {
    public SendTreasureChestInfoClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.TreasureChestInfo> _info = new global::System.Collections.Generic.List<ProtoCmd.TreasureChestInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.TreasureChestInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}