//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpriteCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespondSpriteOperateClientCmd")]
  public partial class RespondSpriteOperateClientCmd : global::ProtoBuf.IExtensible
  {
    public RespondSpriteOperateClientCmd() {}
    
    private uint _op_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private uint _ret = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddGuardianClientCmd")]
  public partial class AddGuardianClientCmd : global::ProtoBuf.IExtensible
  {
    public AddGuardianClientCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _guardian_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guardian_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guardian_type
    {
      get { return _guardian_type; }
      set { _guardian_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveGuardianClientCmd")]
  public partial class RemoveGuardianClientCmd : global::ProtoBuf.IExtensible
  {
    public RemoveGuardianClientCmd() {}
    
    private uint _guardian_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guardian_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guardian_type
    {
      get { return _guardian_type; }
      set { _guardian_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapGuardianClientCmd")]
  public partial class SwapGuardianClientCmd : global::ProtoBuf.IExtensible
  {
    public SwapGuardianClientCmd() {}
    
    private uint _src_guardian_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"src_guardian_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_guardian_type
    {
      get { return _src_guardian_type; }
      set { _src_guardian_type = value; }
    }
    private uint _dest_guardian_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dest_guardian_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_guardian_type
    {
      get { return _dest_guardian_type; }
      set { _dest_guardian_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpriteAttr")]
  public partial class SpriteAttr : global::ProtoBuf.IExtensible
  {
    public SpriteAttr() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpriteData")]
  public partial class SpriteData : global::ProtoBuf.IExtensible
  {
    public SpriteData() {}
    
    private uint _baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _next_exp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"next_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next_exp
    {
      get { return _next_exp; }
      set { _next_exp = value; }
    }
    private bool _is_fight = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"is_fight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_fight
    {
      get { return _is_fight; }
      set { _is_fight = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.SpriteAttr> _attr = new global::System.Collections.Generic.List<ProtoCmd.SpriteAttr>();
    [global::ProtoBuf.ProtoMember(6, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.SpriteAttr> attr
    {
      get { return _attr; }
    }
  
    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _next_peace = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"next_peace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint next_peace
    {
      get { return _next_peace; }
      set { _next_peace = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshSpriteListClientCmd")]
  public partial class RefreshSpriteListClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshSpriteListClientCmd() {}
    
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.SpriteData> _list = new global::System.Collections.Generic.List<ProtoCmd.SpriteData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.SpriteData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateSpriteDataClientCmd")]
  public partial class UpdateSpriteDataClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateSpriteDataClientCmd() {}
    
    private ProtoCmd.SpriteData _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.SpriteData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FeedSpriteClientCmd")]
  public partial class FeedSpriteClientCmd : global::ProtoBuf.IExtensible
  {
    public FeedSpriteClientCmd() {}
    
    private uint _sprite_baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sprite_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sprite_baseid
    {
      get { return _sprite_baseid; }
      set { _sprite_baseid = value; }
    }
    private uint _item_baseid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_baseid
    {
      get { return _item_baseid; }
      set { _item_baseid = value; }
    }
    private uint _num = (uint)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)1)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpriteFightClientCmd")]
  public partial class SpriteFightClientCmd : global::ProtoBuf.IExtensible
  {
    public SpriteFightClientCmd() {}
    
    private uint _sprite_baseid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sprite_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sprite_baseid
    {
      get { return _sprite_baseid; }
      set { _sprite_baseid = value; }
    }
    private bool _is_fight = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_fight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_fight
    {
      get { return _is_fight; }
      set { _is_fight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PromoteSpriteClientCmd")]
  public partial class PromoteSpriteClientCmd : global::ProtoBuf.IExtensible
  {
    public PromoteSpriteClientCmd() {}
    
    private uint _sprite_baseid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sprite_baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sprite_baseid
    {
      get { return _sprite_baseid; }
      set { _sprite_baseid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuaidianType")]
    public enum GuaidianType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_None", Value=0)]
      GuaidianType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_Power", Value=1)]
      GuaidianType_Power = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_Agile", Value=2)]
      GuaidianType_Agile = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_Intell", Value=3)]
      GuaidianType_Intell = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_Body", Value=4)]
      GuaidianType_Body = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_Crit", Value=5)]
      GuaidianType_Crit = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuaidianType_Dodge", Value=6)]
      GuaidianType_Dodge = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpriteAttrType")]
    public enum SpriteAttrType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_None", Value=0)]
      SpriteAttrType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_Power", Value=1)]
      SpriteAttrType_Power = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_Agile", Value=2)]
      SpriteAttrType_Agile = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_Intell", Value=3)]
      SpriteAttrType_Intell = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_Body", Value=4)]
      SpriteAttrType_Body = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_CritLv", Value=5)]
      SpriteAttrType_CritLv = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteAttrType_DodgeLv", Value=6)]
      SpriteAttrType_DodgeLv = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpriteOperateType")]
    public enum SpriteOperateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_None", Value=0)]
      SpriteOperateType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_AddGuardian", Value=1)]
      SpriteOperateType_AddGuardian = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_RemoveGuardian", Value=2)]
      SpriteOperateType_RemoveGuardian = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_SwapGuardian", Value=3)]
      SpriteOperateType_SwapGuardian = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_FeedSprite", Value=4)]
      SpriteOperateType_FeedSprite = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_SpriteFight", Value=5)]
      SpriteOperateType_SpriteFight = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpriteOperateType_Promote", Value=6)]
      SpriteOperateType_Promote = 6
    }
  
}