//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StatCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgInfo")]
  public partial class MsgInfo : global::ProtoBuf.IExtensible
  {
    public MsgInfo() {}
    
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _u32 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"u32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint u32
    {
      get { return _u32; }
      set { _u32 = value; }
    }
    private int _i32 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"i32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int i32
    {
      get { return _i32; }
      set { _i32 = value; }
    }
    private ulong _u64 = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"u64", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong u64
    {
      get { return _u64; }
      set { _u64 = value; }
    }
    private byte[] _s = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"s", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] s
    {
      get { return _s; }
      set { _s = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStatLogReq")]
  public partial class AddStatLogReq : global::ProtoBuf.IExtensible
  {
    public AddStatLogReq() {}
    
    private uint _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private uint _statid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"statid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint statid
    {
      get { return _statid; }
      set { _statid = value; }
    }
    private byte[] _statname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"statname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] statname
    {
      get { return _statname; }
      set { _statname = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.MsgInfo> _infos = new global::System.Collections.Generic.List<ProtoCmd.MsgInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.MsgInfo> infos
    {
      get { return _infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}